In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

data_path = "data"

events = pd.read_csv(os.path.join(data_path, "events.csv"))
order_items = pd.read_csv(os.path.join(data_path, "order_items.csv"))
orders = pd.read_csv(os.path.join(data_path, "orders.csv"))
products = pd.read_csv(os.path.join(data_path, "products.csv"))
users = pd.read_csv(os.path.join(data_path, "users.csv"))

In [3]:
print(events.shape)
# print(inventory_events.shape)
print(order_items.shape)
print(orders.shape)
print(products.shape)
print(users.shape)

(2420661, 13)
(180862, 11)
(124814, 9)
(29120, 9)
(100000, 15)

In [4]:
tables = [events, order_items, orders, products, users]
for table in tables:
    print(f'Some information about table:\n')
    print(table.info())
    print()

Some information about table:

<class 'pandas.DataFrame'>
RangeIndex: 2420661 entries, 0 to 2420660
Data columns (total 13 columns):
 #   Column           Dtype
---  ------           -----
 0   id               int64
 1   user_id          float64
 2   sequence_number  int64
 3   session_id       str
 4   created_at       str
 5   ip_address       str
 6   city             str
 7   state            str
 8   postal_code      str
 9   browser          str
 10  traffic_source   str
 11  uri              str
 12  event_type       str
dtypes: float64(1), int64(2), str(10)
memory usage: 553.4 MB
None

Some information about table:

<class 'pandas.DataFrame'>
RangeIndex: 180862 entries, 0 to 180861
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 180862 non-null  int64
 1   order_id           180862 non-null  int64
 2   user_id            180862 non-null  int64
 3   product_id         180862 non-null  int64
 4   inventory_item_id  180862 non-null  int64
 5   status             180862 non-null  str
 6   created_at         180862 non-null  str
 7   shipped_at         117919 non-null  str
 8   delivered_at       63463 non-null   str
 9   returned_at        18041 non-null   str
 10  sale_price         180862 non-null  float64
dtypes: float64(1), int64(5), str(5)
memory usage: 25.1 MB
None

Some information about table:

<class 'pandas.DataFrame'>
RangeIndex: 124814 entries, 0 to 124813
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      124814 non-null  int64
 1   user_id       124814 non-null  int64
 2   status        124814 non-null  str
 3   gender        124814 non-null  str
 4   created_at    124814 non-null  str
 5   returned_at   12439 non-null   str
 6   shipped_at    81454 non-null   str
 7   delivered_at  43867 non-null   str
 8   num_of_item   124814 non-null  int64
dtypes: int64(3), str(6)
memory usage: 15.5 MB
None

Some information about table:

<class 'pandas.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      29120 non-null  int64
 1   cost                    29120 non-null  float64
 2   category                29120 non-null  str
 3   name                    29118 non-null  str
 4   brand                   29096 non-null  str
 5   retail_price            29120 non-null  float64
 6   department              29120 non-null  str
 7   sku                     29120 non-null  str
 8   distribution_center_id  29120 non-null  int64
dtypes: float64(2), int64(2), str(5)
memory usage: 4.9 MB
None

Some information about table:

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              100000 non-null  int64
 1   first_name      100000 non-null  str
 2   last_name       100000 non-null  str
 3   email           100000 non-null  str
 4   age             100000 non-null  int64
 5   gender          100000 non-null  str
 6   state           100000 non-null  str
 7   street_address  100000 non-null  str
 8   postal_code     100000 non-null  str
 9   city            99045 non-null   str
 10  country         100000 non-null  str
 11  latitude        100000 non-null  float64
 12  longitude       100000 non-null  float64
 13  traffic_source  100000 non-null  str
 14  created_at      100000 non-null  str
dtypes: float64(2), int64(2), str(11)
memory usage: 23.0 MB
None

1. Bảng events

In [5]:
events.head()

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
0,1437486,NaN,3,063af7a0-25c0-46c3-854b-2f3ec3d974ab,2019-04-26 16:02:00 UTC,156.42.243.148,São Paulo,São Paulo,02675-031,Chrome,YouTube,/cancel,cancel
1,2172013,NaN,3,7aa618a9-218d-46d4-ba56-f37092575a06,2022-10-05 16:56:00 UTC,40.155.221.143,São Paulo,São Paulo,02675-031,Chrome,YouTube,/cancel,cancel
2,1987970,NaN,3,1f918350-992c-49dd-82af-f3e72b8b94e4,2021-02-17 04:35:00 UTC,91.237.188.129,São Paulo,São Paulo,02675-031,Safari,Email,/cancel,cancel
3,2245378,NaN,3,8a99bc3c-f70b-4c9a-be26-5313bb226b34,2024-04-07 04:52:00 UTC,147.219.220.175,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
4,1519935,NaN,3,a64f434d-d3f2-4261-a490-79d4743d81e4,2023-09-14 15:20:00 UTC,211.175.27.209,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel

In [6]:
events['created_at'] = pd.to_datetime(events['created_at'], format='mixed', utc=True)

In [7]:
events['user_id'] = events['user_id'].astype('Int64')

In [8]:
events.isna().mean()

id                 0.000000
user_id            0.464554
sequence_number    0.000000
session_id         0.000000
created_at         0.000000
ip_address         0.000000
city               0.009310
state              0.000000
postal_code        0.000000
browser            0.000000
traffic_source     0.000000
uri                0.000000
event_type         0.000000
dtype: float64

user_id null khoảng 46%, đó là anonymous users -> không cần xử lý

In [9]:
events.duplicated().sum()

np.int64(0)

In [10]:
events[events['city'].isna()]

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
150,2138380,<NA>,3,19a38fb7-0656-4313-8d31-4e2a9c935d27,2023-03-14 16:09:00+00:00,113.240.1.107,NaN,Galicia,15174,Chrome,Adwords,/cancel,cancel
276,1418428,<NA>,3,2d91215c-adc4-4cb1-8fbe-116a63e05f29,2022-12-13 15:29:00+00:00,154.67.252.248,NaN,Virginia,22406,Chrome,Adwords,/cancel,cancel
277,1819240,<NA>,3,b3140e30-11ac-4e8d-9996-7be949527b1b,2022-06-28 14:27:00+00:00,165.209.222.137,NaN,Virginia,22408,Chrome,Email,/cancel,cancel
284,1762490,<NA>,3,b004c40e-0ae5-4d9a-a4e7-4179d626ddfa,2022-07-08 11:35:00+00:00,155.205.145.81,NaN,Virginia,22556,Other,Adwords,/cancel,cancel
389,1860552,<NA>,3,160bb51d-4a23-4627-913f-91cdf4f53268,2022-08-15 08:44:00+00:00,92.147.22.168,NaN,Espírito Santo,29142,IE,Facebook,/cancel,cancel
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2420180,969134,74629,7,ddbb4a6f-e93d-4bb6-8b71-b8a23c1be68d,2023-11-10 00:53:49+00:00,152.106.107.165,NaN,Amazonas,69735-000,Firefox,Adwords,/purchase,purchase
2420181,825529,63400,10,0e8a952c-432f-4a7a-bbd5-7dd9d4da2520,2021-07-27 07:02:35+00:00,122.75.126.127,NaN,Acre,69980-000,Chrome,Email,/purchase,purchase
2420254,210938,16217,7,c232b619-9f5c-4369-8be5-d3c3bd735a58,2022-06-05 13:23:50+00:00,175.94.30.79,NaN,Goiás,73900-000,Chrome,Email,/purchase,purchase
2420339,52104,3826,7,f1a57705-a495-49d3-99c7-6815a9bf01a8,2024-01-18 02:42:54+00:00,66.189.96.131,NaN,Mato Grosso,78850-000,Safari,Adwords,/purchase,purchase
2420408,638029,48783,5,5390033e-e462-4e3d-9c85-371dd61a73de,2023-03-05 00:57:52+00:00,100.51.4.184,NaN,Paraná,84600-000,Chrome,Email,/purchase,purchase

In [11]:
events.columns

Index(['id', 'user_id', 'sequence_number', 'session_id', 'created_at',
       'ip_address', 'city', 'state', 'postal_code', 'browser',
       'traffic_source', 'uri', 'event_type'],
      dtype='str')

In [12]:
list(events['uri'].unique())

['/cancel',
 '/cart',
 '/department/men/category/pants/brand/americanapparel',
 '/department/women/category/intimates/brand/laura',
 '/department/men/category/fashionhoodies&sweatshirts/brand/ililily',
 '/department/men/category/tops&tees/brand/hollister',
 '/department/women/category/socks&hosiery/brand/hotchillys',
 '/department/women/category/socks&hosiery/brand/lifeisgood',
 '/department/men/category/underwear/brand/c-in2',
 '/department/women/category/maternity/brand/prego',
 '/department/women/category/active/brand/adidas',
 '/department/men/category/outerwear&coats/brand/portauthority',
 '/department/women/category/outerwear&coats/brand/carhartt',
 '/department/men/category/underwear/brand/rounderbum',
 '/department/men/category/pants/brand/dockers',
 '/department/men/category/outerwear&coats/brand/kennethcole',
 '/department/women/category/shorts/brand/rewash',
 '/department/women/category/dresses/brand/calvinklein',
 '/department/men/category/tops&tees/brand/volcom',
 '/department/women/category/sweaters/brand/bench',
 '/department/women/category/intimates/brand/bslingerie',
 '/department/men/category/fashionhoodies&sweatshirts/brand/unionbay',
 '/department/men/category/underwear/brand/jockey',
 "/department/women/category/jeans/brand/levi's",
 '/department/men/category/fashionhoodies&sweatshirts/brand/hottopic',
 '/department/women/category/dresses/brand/ellamoss',
 '/department/women/category/pants&capris/brand/xoxo',
 '/department/men/category/fashionhoodies&sweatshirts/brand/truereligion',
 '/department/women/category/intimates/brand/rago',
 '/department/women/category/skirts/brand/finebrandshop',
 '/department/men/category/pants/brand/edgarments',
 '/department/men/category/accessories/brand/carhartt',
 '/department/women/category/maternity/brand/momomaternity',
 '/department/men/category/shorts/brand/dickies',
 '/department/women/category/intimates/brand/vanityfair',
 '/department/men/category/outerwear&coats/brand/carhartt',
 '/department/women/category/intimates/brand/gemsli',
 '/department/men/category/jeans/brand/7forallmankind',
 "/department/men/category/shorts/brand/levi's",
 '/department/women/category/outerwear&coats/brand/patty',
 '/department/men/category/active/brand/nike',
 '/department/women/category/pants&capris/brand/alight',
 '/department/men/category/sleep&lounge/brand/dfdesigns',
 '/department/women/category/accessories/brand/oakley',
 '/department/women/category/sleep&lounge/brand/hue',
 '/department/men/category/sleep&lounge/brand/izod',
 '/department/women/category/tops&tees/brand/chemisettesbyanne',
 '/department/men/category/suits&sportcoats/brand/seanjohn',
 '/department/men/category/outerwear&coats/brand/kennethcolereaction',
 '/department/women/category/accessories/brand/serengeti',
 '/department/men/category/fashionhoodies&sweatshirts/brand/hoodiebuddie',
 '/department/women/category/socks&hosiery/brand/smartwool',
 '/department/men/category/pants/brand/tru-spec',
 '/department/women/category/fashionhoodies&sweatshirts/brand/abbeydawn',
 '/department/women/category/sleep&lounge/brand/hatley',
 '/department/women/category/accessories/brand/gemavenue',
 '/department/women/category/shorts/brand/dl1961',
 '/department/men/category/socks/brand/adidas',
 '/department/men/category/sweaters/brand/orvis',
 '/department/women/category/maternity/brand/lamaze',
 '/department/men/category/jeans/brand/buffalobydavidbitton',
 "/department/men/category/outerwear&coats/brand/levi's",
 '/department/men/category/outerwear&coats/brand/seanjohn',
 '/department/men/category/sleep&lounge/brand/dockers',
 '/department/men/category/swim/brand/tyr',
 '/department/men/category/pants/brand/kingsize',
 '/department/women/category/fashionhoodies&sweatshirts/brand/mod-o-doc',
 '/department/men/category/sweaters/brand/smartwool',
 '/department/women/category/accessories/brand/trendsblue',
 '/department/women/category/active/brand/thorlo',
 '/department/women/category/shorts/brand/edgarments',
 '/department/men/category/pants/brand/haggar',
 '/department/women/category/sweaters/brand/d.e.p.t.',
 '/department/women/category/skirts/brand/americanapparel',
 '/department/women/category/skirts/brand/carvedesigns',
 '/department/women/category/sweaters/brand/hollywoodstarfashion',
 '/department/men/category/shorts/brand/frenchconnection',
 '/department/men/category/fashionhoodies&sweatshirts/brand/allegrak',
 '/department/women/category/fashionhoodies&sweatshirts/brand/activewearapparel',
 '/department/men/category/socks/brand/timberland',
 '/department/men/category/socks/brand/dickies',
 '/department/men/category/fashionhoodies&sweatshirts/brand/volcom',
 '/department/women/category/tops&tees/brand/calvinklein',
 '/department/women/category/maternity/brand/allegrak',
 '/department/men/category/suits&sportcoats/brand/dockers',
 '/department/men/category/outerwear&coats/brand/membersonly',
 '/department/women/category/sleep&lounge/brand/carolwrightgifts',
 "/department/women/category/leggings/brand/vivian'sfashions",
 '/department/men/category/suits&sportcoats/brand/cianni',
 '/department/women/category/leggings/brand/an1225',
 '/department/women/category/accessories/brand/ralphbyralphlauren',
 '/department/men/category/accessories/brand/dc',
 '/department/men/category/swim/brand/quiksilver',
 '/department/men/category/pants/brand/walls',
 '/department/men/category/pants/brand/j.c.rags',
 '/department/men/category/accessories/brand/toktokdesigns',
 '/department/men/category/jeans/brand/gbyguess',
 '/department/men/category/underwear/brand/calvinklein',
 '/department/men/category/underwear/brand/carhartt',
 '/department/men/category/active/brand/tri-mountain',
 '/department/women/category/swim/brand/aloha',
 '/department/men/category/suits&sportcoats/brand/y&g',
 "/department/women/category/jeans/brand/notyourdaughter'sjeans",
 '/department/women/category/intimates/brand/bodywrap',
 '/department/men/category/jeans/brand/hudson',
 '/department/men/category/sleep&lounge/brand/diesel',
 '/department/women/category/intimates/brand/eberjey',
 '/department/men/category/tops&tees/brand/carhartt',
 '/department/women/category/intimates/brand/dr.reyshapewear',
 '/department/men/category/pants/brand/geoffreybeene',
 '/department/women/category/jeans/brand/7forallmankind',
 '/department/men/category/tops&tees/brand/smartwool',
 '/department/men/category/active/brand/icebreaker',
 '/department/women/category/fashionhoodies&sweatshirts/brand/westernexpress',
 '/department/women/category/fashionhoodies&sweatshirts/brand/claeson',
 '/department/women/category/jeans/brand/silverjeans',
 '/department/women/category/jeans/brand/womanwithin',
 '/department/men/category/sleep&lounge/brand/hanro',
 '/department/women/category/sleep&lounge/brand/natori',
 '/department/men/category/accessories/brand/poloralphlauren',
 '/department/men/category/active/brand/underarmour',
 '/department/men/category/fashionhoodies&sweatshirts/brand/quiksilver',
 '/department/men/category/active/brand/hanes',
 "/department/men/category/jeans/brand/joe'sjeans",
 '/department/women/category/intimates/brand/natori',
 '/department/men/category/swim/brand/onia',
 '/department/men/category/fashionhoodies&sweatshirts/brand/codev',
 '/department/men/category/pants/brand/thesavilerowcompany',
 '/department/women/category/swim/brand/carmenmarcvalvo',
 '/department/men/category/jeans/brand/volcom',
 '/department/women/category/intimates/brand/coquette',
 '/department/women/category/sweaters/brand/evoguesapparel',
 '/department/men/category/fashionhoodies&sweatshirts/brand/harley-davidson',
 '/department/men/category/tops&tees/brand/woolrich',
 '/department/women/category/leggings/brand/vipboutique',
 '/department/women/category/fashionhoodies&sweatshirts/brand/hottopic',
 '/department/women/category/shorts/brand/allegrak',
 '/department/men/category/active/brand/asics',
 '/department/women/category/maternity/brand/mermaidmaternity',
 '/department/women/category/leggings/brand/donnakaran',
 '/department/men/category/pants/brand/orvis',
 '/department/women/category/intimates/brand/hanes',
 '/department/women/category/intimates/brand/morriscostumes',
 '/department/men/category/sweaters/brand/nautica',
 '/department/women/category/sleep&lounge/brand/hellokitty',
 '/department/men/category/sweaters/brand/arrow',
 '/department/men/category/underwear/brand/tommyhilfiger',
 '/department/men/category/fashionhoodies&sweatshirts/brand/n2nbodywear',
 '/department/men/category/fashionhoodies&sweatshirts/brand/truegrit',
 '/department/women/category/plus/brand/foottraffic',
 '/department/men/category/sweaters/brand/unionbay',
 '/department/men/category/tops&tees/brand/a:xarmaniexchange',
 '/department/women/category/sleep&lounge/brand/nicolemiller',
 '/department/women/category/socks&hosiery/brand/comfortchoice',
 '/department/women/category/pants&capris/brand/dockers',
 '/department/women/category/plus/brand/ames',
 '/department/women/category/dresses/brand/danny&nicole',
 '/department/women/category/fashionhoodies&sweatshirts/brand/finebrandshop',
 '/department/men/category/tops&tees/brand/lrg',
 '/department/women/category/socks&hosiery/brand/goldtoe',
 '/department/men/category/underwear/brand/cua',
 '/department/men/category/jeans/brand/diesel',
 '/department/women/category/active/brand/duofold',
 '/department/women/category/intimates/brand/adriana',
 '/department/women/category/intimates/brand/jockey',
 '/department/men/category/socks/brand/aetrex',
 '/department/women/category/socks&hosiery/brand/foottraffic',
 '/department/women/category/accessories/brand/coolibar',
 '/department/women/category/active/brand/cuddlduds',
 '/department/men/category/tops&tees/brand/aeropostale',
 '/department/women/category/maternity/brand/c-panty',
 '/department/men/category/tops&tees/brand/columbia',
 '/department/women/category/pants&capris/brand/lotustraders',
 '/department/women/category/dresses/brand/hotfromhollywood',
 '/department/men/category/shorts/brand/clubroom',
 '/department/women/category/fashionhoodies&sweatshirts/brand/lifeisgood',
 '/department/men/category/swim/brand/reef',
 '/department/women/category/leggings/brand/dc',
 '/department/women/category/maternity/brand/everlygrey',
 '/department/men/category/swim/brand/fox',
 '/department/women/category/leggings/brand/torrid',
 '/department/women/category/jeans/brand/wrangler',
 '/department/men/category/suits&sportcoats/brand/jonesnewyork',
 '/department/men/category/tops&tees/brand/dc',
 '/department/women/category/fashionhoodies&sweatshirts/brand/sailorjerry',
 '/department/men/category/pants/brand/sansabelt',
 '/department/men/category/accessories/brand/tommyhilfiger',
 '/department/women/category/sleep&lounge/brand/samanthasstyleshoppe',
 '/department/men/category/swim/brand/vilebrequin',
 '/department/women/category/sleep&lounge/brand/aegean',
 '/department/men/category/suits&sportcoats/brand/giorgiocerruti',
 '/department/men/category/accessories/brand/nike',
 '/department/men/category/underwear/brand/hanes',
 '/department/men/category/pants/brand/perryellis',
 '/department/men/category/swim/brand/finis',
 '/department/men/category/sweaters/brand/paulfredrick',
 '/department/women/category/leggings/brand/stellaelyse',
 '/department/men/category/socks/brand/royal',
 '/department/men/category/outerwear&coats/brand/nobis',
 '/department/men/category/suits&sportcoats/brand/kennethcolereaction',
 '/department/women/category/outerwear&coats/brand/gbyguess',
 '/department/women/category/sleep&lounge/brand/dogisgood',
 '/department/women/category/sleep&lounge/brand/carolehochman',
 '/department/women/category/leggings/brand/allegrak',
 '/department/men/category/fashionhoodies&sweatshirts/brand/nextlevel',
 '/department/men/category/outerwear&coats/brand/londonfog',
 '/department/women/category/maternity/brand/olian',
 '/department/men/category/sweaters/brand/portauthority',
 '/department/women/category/blazers&jackets/brand/allegrak',
 '/department/men/category/tops&tees/brand/vanheusen',
 '/department/men/category/tops&tees/brand/oakley',
 '/department/women/category/plus/brand/smartwool',
 '/department/men/category/accessories/brand/gucci',
 '/department/men/category/socks/brand/icebreaker',
 '/department/women/category/dresses/brand/allegrak',
 '/department/women/category/intimates/brand/calvinklein',
 '/department/men/category/fashionhoodies&sweatshirts/brand/nirvana',
 '/department/women/category/swim/brand/hotfromhollywood',
 '/department/men/category/outerwear&coats/brand/allegrak',
 '/department/men/category/shorts/brand/quiksilver',
 '/department/men/category/outerwear&coats/brand/mountainhardwear',
 '/department/women/category/sweaters/brand/ellamoss',
 '/department/men/category/suits&sportcoats/brand/paulmalone',
 '/department/men/category/shorts/brand/wrangler',
 '/department/men/category/swim/brand/coolibar',
 '/department/men/category/accessories/brand/pearlizumi',
 '/department/women/category/sweaters/brand/ralphlauren',
 '/department/men/category/underwear/brand/fruitoftheloom',
 '/department/men/category/socks/brand/puma',
 '/department/women/category/tops&tees/brand/xoxo',
 '/department/women/category/outerwear&coats/brand/barbour',
 '/department/women/category/leggings/brand/hollywoodstarfashion',
 '/department/men/category/suits&sportcoats/brand/tommyhilfiger',
 '/department/men/category/fashionhoodies&sweatshirts/brand/tapout',
 '/department/women/category/active/brand/champion',
 '/department/women/category/intimates/brand/bali',
 '/department/men/category/socks/brand/calvinklein',
 '/department/women/category/sweaters/brand/merrell',
 '/department/men/category/jeans/brand/wrangler',
 '/department/women/category/jumpsuits&rompers/brand/allegrak',
 '/department/women/category/jeans/brand/paige',
 '/department/women/category/outerwear&coats/brand/u.s.poloassn.',
 '/department/women/category/pants&capris/brand/calvinklein',
 '/department/men/category/sweaters/brand/theory',
 '/department/men/category/suits&sportcoats/brand/brandq',
 '/department/men/category/active/brand/browning',
 '/department/women/category/blazers&jackets/brand/karenkane',
 '/department/men/category/jeans/brand/jack',
 '/department/women/category/intimates/brand/ilusion',
 '/department/men/category/tops&tees/brand/cubavera',
 '/department/men/category/fashionhoodies&sweatshirts/brand/matix',
 '/department/men/category/underwear/brand/gregghomme',
 '/department/women/category/socks&hosiery/brand/snoozies',
 '/department/men/category/pants/brand/allegrak',
 '/department/men/category/tops&tees/brand/dickies',
 '/department/women/category/swim/brand/jag',
 '/department/men/category/tops&tees/brand/subculture',
 '/department/women/category/leggings/brand/thelees',
 '/department/men/category/fashionhoodies&sweatshirts/brand/akomplice',
 '/department/women/category/sweaters/brand/samanthasstyleshoppe',
 '/department/men/category/fashionhoodies&sweatshirts/brand/grenade',
 '/department/women/category/shorts/brand/2bbybebe',
 '/department/women/category/tops&tees/brand/activeproducts',
 '/department/women/category/sleep&lounge/brand/betseyjohnson',
 '/department/men/category/socks/brand/reebok',
 '/department/women/category/maternity/brand/motherhoodmaternity',
 '/department/women/category/suits/brand/ice',
 '/department/men/category/socks/brand/goldtoe',
 '/department/women/category/sweaters/brand/calvinkleinjeans',
 '/department/men/category/suits&sportcoats/brand/marceckocut&sew',
 '/department/women/category/fashionhoodies&sweatshirts/brand/activeproducts',
 '/department/men/category/fashionhoodies&sweatshirts/brand/edhardy',
 '/department/women/category/maternity/brand/mommyparadise',
 '/department/men/category/suits&sportcoats/brand/kingformalwear',
 '/department/men/category/tops&tees/brand/ultraclub',
 '/department/women/category/plus/brand/movingcomfort',
 '/department/women/category/shorts/brand/billabong',
 '/department/men/category/underwear/brand/indera',
 '/department/women/category/intimates/brand/glamorise',
 '/department/men/category/socks/brand/footjoy',
 '/department/men/category/active/brand/harriton',
 '/department/men/category/jeans/brand/truereligion',
 '/department/men/category/sleep&lounge/brand/majesticinternational',
 '/department/men/category/sweaters/brand/kennethcole',
 '/department/women/category/skirts/brand/2bbybebe',
 '/department/women/category/tops&tees/brand/harvardsquare',
 '/department/women/category/outerwear&coats/brand/joujou',
 '/department/men/category/sleep&lounge/brand/alexanderdelrossa',
 '/department/men/category/jeans/brand/luckybrand',
 '/department/men/category/shorts/brand/allegrak',
 '/department/women/category/socks&hosiery/brand/ninewest',
 '/department/women/category/tops&tees/brand/tri-mountain',
 '/department/men/category/underwear/brand/dockers',
 '/department/women/category/fashionhoodies&sweatshirts/brand/allegrak',
 '/department/women/category/swim/brand/reebok',
 '/department/women/category/swim/brand/beccabyrebeccavirtue',
 "/department/men/category/jeans/brand/levi's",
 '/department/women/category/plus/brand/boxed-gifts',
 '/department/men/category/accessories/brand/beardski',
 '/department/men/category/shorts/brand/lee',
 '/department/men/category/active/brand/thorlo',
 '/department/men/category/fashionhoodies&sweatshirts/brand/nittanyoutlet',
 '/department/women/category/skirts/brand/mapleclothing',
 '/department/men/category/tops&tees/brand/shirt.woot',
 '/department/women/category/maternity/brand/apeainthepod',
 '/department/men/category/tops&tees/brand/quiksilver',
 '/department/women/category/leggings/brand/jonesnewyork',
 '/department/women/category/fashionhoodies&sweatshirts/brand/ladyhathaway',
 '/department/men/category/outerwear&coats/brand/tommyhilfiger',
 '/department/women/category/intimates/brand/rampage',
 '/department/women/category/pants&capris/brand/ans',
 '/department/women/category/swim/brand/speedo',
 '/department/women/category/intimates/brand/intimatesboutique',
 '/department/men/category/jeans/brand/matix',
 '/department/men/category/underwear/brand/harborbay',
 '/department/men/category/outerwear&coats/brand/columbia',
 '/department/men/category/jeans/brand/guidegear',
 '/department/men/category/tops&tees/brand/ashcity',
 '/department/men/category/socks/brand/pearlizumi',
 '/department/men/category/sleep&lounge/brand/intimo',
 '/department/women/category/plus/brand/cashmerepashminagroup',
 '/department/men/category/fashionhoodies&sweatshirts/brand/burnside',
 '/department/women/category/tops&tees/brand/hollywoodstarfashion',
 '/department/women/category/intimates/brand/vivilli',
 "/department/women/category/sleep&lounge/brand/thecat'spajamas",
 '/department/men/category/socks/brand/sockguy',
 '/department/men/category/tops&tees/brand/exofficio',
 '/department/women/category/accessories/brand/foxriversocks',
 '/department/women/category/socks&hosiery/brand/hanes',
 '/department/women/category/outerwear&coats/brand/columbia',
 '/department/women/category/tops&tees/brand/carhartt',
 '/department/men/category/socks/brand/goodhew',
 '/department/men/category/underwear/brand/bjornborg',
 '/department/men/category/fashionhoodies&sweatshirts/brand/districtthreads',
 '/department/men/category/shorts/brand/savane',
 '/department/men/category/underwear/brand/2(x)ist',
 '/department/men/category/tops&tees/brand/hanes',
 '/department/men/category/shorts/brand/izod',
 '/department/women/category/pants&capris/brand/roxy',
 '/department/men/category/socks/brand/hugoboss',
 '/department/men/category/sweaters/brand/j.c.rags',
 '/department/men/category/sweaters/brand/mcalister',
 '/department/men/category/tops&tees/brand/originalpenguin',
 '/department/men/category/shorts/brand/lorddaniels',
 '/department/women/category/intimates/brand/barelythere',
 '/department/men/category/outerwear&coats/brand/volcom',
 '/department/men/category/swim/brand/garymajdellsport',
 '/department/women/category/leggings/brand/skhatshop',
 '/department/women/category/active/brand/asics',

Parse cột URI để tách department, category, brand.... của product

In [13]:
dict(events['uri'].value_counts())

{'/cart': np.int64(592374),
 '/purchase': np.int64(180862),
 '/cancel': np.int64(124801),
 '/home': np.int64(87406),
 '/department/women/category/maternity/brand/motherhoodmaternity': np.int64(3341),
 '/department/women/category/blazers&jackets/brand/allegrak': np.int64(2836),
 '/department/men/category/jeans/brand/wrangler': np.int64(2739),
 '/department/men/category/swim/brand/quiksilver': np.int64(2334),
 '/department/women/category/dresses/brand/allegrak': np.int64(2269),
 "/department/women/category/jeans/brand/levi's": np.int64(2225),
 '/department/men/category/underwear/brand/calvinklein': np.int64(2186),
 '/department/men/category/pants/brand/dockers': np.int64(2174),
 '/department/men/category/underwear/brand/hanes': np.int64(2171),
 '/department/women/category/swim/brand/speedo': np.int64(2061),
 '/department/men/category/outerwear&coats/brand/carhartt': np.int64(2058),
 '/department/men/category/swim/brand/speedo': np.int64(1977),
 '/department/men/category/pants/brand/allegrak': np.int64(1953),
 '/department/men/category/jeans/brand/7forallmankind': np.int64(1920),
 '/department/women/category/tops&tees/brand/allegrak': np.int64(1758),
 '/department/men/category/jeans/brand/diesel': np.int64(1550),
 "/department/men/category/swim/brand/o'neill": np.int64(1518),
 "/department/women/category/jeans/brand/notyourdaughter'sjeans": np.int64(1447),
 '/department/men/category/sleep&lounge/brand/nautica': np.int64(1431),
 '/department/men/category/underwear/brand/fruitoftheloom': np.int64(1396),
 '/department/men/category/active/brand/champion': np.int64(1382),
 '/department/women/category/fashionhoodies&sweatshirts/brand/allegrak': np.int64(1369),
 '/department/women/category/intimates/brand/bali': np.int64(1357),
 '/department/men/category/pants/brand/haggar': np.int64(1355),
 '/department/women/category/intimates/brand/hanes': np.int64(1321),
 "/department/men/category/jeans/brand/joe'sjeans": np.int64(1312),
 '/department/women/category/shorts/brand/allegrak': np.int64(1311),
 '/department/women/category/intimates/brand/maidenform': np.int64(1303),
 '/department/men/category/accessories/brand/ray-ban': np.int64(1299),
 '/department/men/category/sleep&lounge/brand/majesticinternational': np.int64(1276),
 '/department/men/category/sleep&lounge/brand/hugoboss': np.int64(1270),
 '/department/women/category/jumpsuits&rompers/brand/allegrak': np.int64(1254),
 '/department/men/category/active/brand/adidas': np.int64(1250),
 '/department/men/category/underwear/brand/jockey': np.int64(1193),
 '/department/men/category/shorts/brand/quiksilver': np.int64(1157),
 '/department/men/category/underwear/brand/diesel': np.int64(1152),
 '/department/women/category/jeans/brand/7forallmankind': np.int64(1135),
 '/department/men/category/jeans/brand/truereligion': np.int64(1132),
 '/department/men/category/outerwear&coats/brand/columbia': np.int64(1115),
 '/department/men/category/suits&sportcoats/brand/allegrak': np.int64(1111),
 '/department/women/category/intimates/brand/laura': np.int64(1105),
 '/department/men/category/tops&tees/brand/carhartt': np.int64(1104),
 '/department/women/category/active/brand/champion': np.int64(1076),
 '/department/men/category/shorts/brand/hurley': np.int64(1049),
 '/department/men/category/jeans/brand/luckybrand': np.int64(1047),
 '/department/men/category/fashionhoodies&sweatshirts/brand/allegrak': np.int64(1019),
 '/department/women/category/intimates/brand/sexnight': np.int64(1017),
 '/department/men/category/swim/brand/garymajdellsport': np.int64(1016),
 '/department/men/category/accessories/brand/oakley': np.int64(987),
 '/department/men/category/sweaters/brand/calvinklein': np.int64(983),
 '/department/men/category/underwear/brand/2(x)ist': np.int64(979),
 '/department/women/category/intimates/brand/vanityfair': np.int64(968),
 '/department/men/category/swim/brand/hurley': np.int64(953),
 '/department/women/category/intimates/brand/ilusion': np.int64(942),
 '/department/women/category/socks&hosiery/brand/hue': np.int64(936),
 '/department/men/category/underwear/brand/c-in2': np.int64(927),
 '/department/women/category/accessories/brand/ray-ban': np.int64(925),
 "/department/men/category/sweaters/brand/thelittlealpaca'shouse": np.int64(916),
 '/department/women/category/dresses/brand/hotfromhollywood': np.int64(911),
 '/department/women/category/intimates/brand/wacoal': np.int64(908),
 '/department/women/category/maternity/brand/apeainthepod': np.int64(900),
 '/department/women/category/intimates/brand/calvinklein': np.int64(893),
 '/department/men/category/underwear/brand/duofold': np.int64(875),
 '/department/men/category/underwear/brand/hugoboss': np.int64(875),
 '/department/women/category/tops&tees/brand/patty': np.int64(873),
 '/department/women/category/maternity/brand/threeseasonsmaternity': np.int64(872),
 '/department/men/category/shorts/brand/dickies': np.int64(866),
 '/department/men/category/suits&sportcoats/brand/kingformalwear': np.int64(866),
 '/department/men/category/sleep&lounge/brand/bottomsout': np.int64(865),
 '/department/men/category/pants/brand/savane': np.int64(861),
 '/department/men/category/socks/brand/goldtoe': np.int64(855),
 '/department/men/category/sweaters/brand/tommyhilfiger': np.int64(846),
 '/department/women/category/leggings/brand/allegrak': np.int64(843),
 '/department/men/category/fashionhoodies&sweatshirts/brand/dc': np.int64(840),
 '/department/women/category/active/brand/adidas': np.int64(831),
 '/department/women/category/fashionhoodies&sweatshirts/brand/roxy': np.int64(825),
 '/department/women/category/intimates/brand/bslingerie': np.int64(821),
 "/department/men/category/jeans/brand/levi's": np.int64(810),
 '/department/men/category/suits&sportcoats/brand/tommyhilfiger': np.int64(806),
 '/department/men/category/tops&tees/brand/volcom': np.int64(805),
 '/department/men/category/swim/brand/volcom': np.int64(795),
 '/department/men/category/socks/brand/smartwool': np.int64(792),
 '/department/men/category/fashionhoodies&sweatshirts/brand/fox': np.int64(784),
 '/department/men/category/sweaters/brand/allegrak': np.int64(761),
 '/department/men/category/swim/brand/billabong': np.int64(758),
 '/department/men/category/sleep&lounge/brand/americanessentials': np.int64(754),
 "/department/women/category/intimates/brand/frederick'sofhollywood": np.int64(746),
 '/department/women/category/intimates/brand/flexees': np.int64(744),
 '/department/men/category/socks/brand/thorlo': np.int64(742),
 '/department/men/category/fashionhoodies&sweatshirts/brand/quiksilver': np.int64(740),
 '/department/men/category/active/brand/carhartt': np.int64(739),
 '/department/men/category/tops&tees/brand/u.s.poloassn.': np.int64(739),
 '/department/men/category/socks/brand/hanes': np.int64(735),
 '/department/men/category/sleep&lounge/brand/tommybahama': np.int64(733),
 '/department/men/category/tops&tees/brand/vanheusen': np.int64(730),
 '/department/men/category/socks/brand/wigwam': np.int64(727),
 '/department/men/category/socks/brand/hugoboss': np.int64(726),
 '/department/women/category/fashionhoodies&sweatshirts/brand/fox': np.int64(714),
 '/department/men/category/jeans/brand/hottopic': np.int64(711),
 '/department/women/category/swim/brand/roxy': np.int64(694),
 '/department/women/category/intimates/brand/fruitoftheloom': np.int64(692),
 '/department/men/category/jeans/brand/carhartt': np.int64(692),
 '/department/women/category/intimates/brand/barelythere': np.int64(686),
 '/department/women/category/swim/brand/seafolly': np.int64(681),
 '/department/women/category/pants&capris/brand/jonesnewyork': np.int64(681),
 '/department/men/category/suits&sportcoats/brand/haggar': np.int64(675),
 '/department/men/category/suits&sportcoats/brand/josephabboud': np.int64(674),
 '/department/men/category/active/brand/russellathletic': np.int64(671),
 '/department/men/category/accessories/brand/carhartt': np.int64(670),
 '/department/women/category/intimates/brand/fashionforms': np.int64(670),
 '/department/men/category/tops&tees/brand/dc': np.int64(667),
 '/department/women/category/leggings/brand/skhatshop': np.int64(665),
 '/department/men/category/tops&tees/brand/harley-davidson': np.int64(660),
 '/department/women/category/jeans/brand/truereligion': np.int64(652),
 '/department/men/category/pants/brand/orvis': np.int64(651),
 '/department/women/category/jeans/brand/calvinkleinjeans': np.int64(645),
 '/department/women/category/socks&hosiery/brand/hanes': np.int64(642),
 '/department/women/category/pants&capris/brand/allegrak': np.int64(642),
 "/department/men/category/shorts/brand/o'neill": np.int64(642),
 '/department/men/category/jeans/brand/volcom': np.int64(638),
 '/department/women/category/sleep&lounge/brand/hue': np.int64(636),
 '/department/men/category/accessories/brand/thetiebar': np.int64(632),
 '/department/women/category/jeans/brand/luckybrand': np.int64(629),
 '/department/women/category/jeans/brand/lee': np.int64(625),
 '/department/men/category/fashionhoodies&sweatshirts/brand/hurley': np.int64(621),
 '/department/women/category/fashionhoodies&sweatshirts/brand/volcom': np.int64(621),
 '/department/men/category/pants/brand/perryellis': np.int64(620),
 '/department/men/category/underwear/brand/emporioarmani': np.int64(618),
 '/department/men/category/active/brand/columbia': np.int64(617),
 "/department/women/category/jeans/brand/joe'sjeans": np.int64(615),
 '/department/men/category/pants/brand/calvinklein': np.int64(613),
 '/department/men/category/tops&tees/brand/tommyhilfiger': np.int64(613),
 '/department/women/category/plus/brand/ray-ban': np.int64(605),
 '/department/women/category/sleep&lounge/brand/hellokitty': np.int64(604),
 '/department/men/category/jeans/brand/lee': np.int64(602),
 '/department/men/category/pants/brand/louisraphael': np.int64(599),
 '/department/women/category/suits/brand/evanpicone': np.int64(597),
 '/department/women/category/outerwear&coats/brand/columbia': np.int64(593),
 '/department/women/category/intimates/brand/cosabella': np.int64(591),
 '/department/men/category/outerwear&coats/brand/kennethcole': np.int64(589),
 '/department/men/category/fashionhoodies&sweatshirts/brand/volcom': np.int64(584),
 '/department/women/category/intimates/brand/jockey': np.int64(584),
 '/department/women/category/active/brand/smartwool': np.int64(582),
 '/department/men/category/active/brand/nike': np.int64(580),
 '/department/women/category/sleep&lounge/brand/casualmoments': np.int64(579),
 '/department/men/category/outerwear&coats/brand/calvinklein': np.int64(566),
 '/department/men/category/fashionhoodies&sweatshirts/brand/hottopic': np.int64(564),
 '/department/men/category/swim/brand/kanusurf': np.int64(560),
 "/department/men/category/outerwear&coats/brand/levi's": np.int64(557),
 '/department/men/category/shorts/brand/wrangler': np.int64(557),
 '/department/women/category/leggings/brand/anna-kaci': np.int64(557),
 '/department/women/category/intimates/brand/playtex': np.int64(557),
 '/department/men/category/sleep&lounge/brand/knothecorp.': np.int64(555),
 '/department/women/category/maternity/brand/ripematernity': np.int64(553),
 '/department/men/category/suits&sportcoats/brand/calvinklein': np.int64(553),
 '/department/women/category/sleep&lounge/brand/dreams': np.int64(546),
 '/department/women/category/intimates/brand/felina': np.int64(545),
 '/department/men/category/sleep&lounge/brand/hanro': np.int64(544),
 '/department/women/category/intimates/brand/braza': np.int64(539),
 '/department/women/category/suits/brand/lesuit': np.int64(538),
 '/department/men/category/suits&sportcoats/brand/y&g': np.int64(533),
 '/department/women/category/sleep&lounge/brand/nautica': np.int64(532),
 '/department/women/category/jeans/brand/silverjeans': np.int64(531),
 '/department/women/category/jeans/brand/paige': np.int64(531),
 '/department/women/category/fashionhoodies&sweatshirts/brand/hurley': np.int64(531),
 '/department/women/category/blazers&jackets/brand/suttonstudio': np.int64(528),
 '/department/women/category/accessories/brand/trendsblue': np.int64(525),
 '/department/men/category/tops&tees/brand/columbia': np.int64(524),
 '/department/women/category/swim/brand/miraclesuit': np.int64(524),
 '/department/men/category/pants/brand/geoffreybeene': np.int64(523),
 '/department/women/category/shorts/brand/americanapparel': np.int64(521),
 '/department/women/category/pants&capris/brand/alfreddunner': np.int64(518),
 '/department/men/category/sweaters/brand/fredperry': np.int64(514),
 '/department/men/category/suits&sportcoats/brand/paulfredrick': np.int64(514),
 '/department/men/category/sweaters/brand/nautica': np.int64(513),
 '/department/men/category/shorts/brand/izod': np.int64(513),
 '/department/men/category/tops&tees/brand/hurley': np.int64(512),
 '/department/women/category/suits/brand/kasper': np.int64(511),
 '/department/men/category/shorts/brand/allegrak': np.int64(510),
 '/department/men/category/sweaters/brand/perryellis': np.int64(510),
 '/department/women/category/shorts/brand/roxy': np.int64(510),
 '/department/women/category/leggings/brand/leggingsqueen': np.int64(508),
 '/department/men/category/fashionhoodies&sweatshirts/brand/metalmulisha': np.int64(506),
 '/department/men/category/sweaters/brand/paulfredrick': np.int64(504),
 '/department/men/category/suits&sportcoats/brand/ralphlauren': np.int64(502),
 '/department/men/category/jeans/brand/dickies': np.int64(501),
 '/department/men/category/socks/brand/k.bell': np.int64(501),
 '/department/women/category/intimates/brand/vivilli': np.int64(499),
 '/department/women/category/sweaters/brand/patty': np.int64(499),
 '/department/women/category/dresses/brand/calvinklein': np.int64(498),
 '/department/women/category/tops&tees/brand/luckybrand': np.int64(498),
 '/department/women/category/sleep&lounge/brand/alexanderdelrossa': np.int64(497),
 '/department/men/category/fashionhoodies&sweatshirts/brand/retrofit': np.int64(496),
 '/department/men/category/outerwear&coats/brand/mountainhardwear': np.int64(495),
 '/department/men/category/active/brand/hanes': np.int64(494),
 '/department/women/category/suits/brand/ice': np.int64(490),
 '/department/men/category/sleep&lounge/brand/intimo': np.int64(490),
 '/department/women/category/socks&hosiery/brand/skhatshop': np.int64(490),
 '/department/men/category/shorts/brand/fox': np.int64(490),
 '/department/men/category/sleep&lounge/brand/spa&resort': np.int64(490),
 '/department/women/category/intimates/brand/anna-kaci': np.int64(488),
 '/department/men/category/jeans/brand/g-star': np.int64(488),
 '/department/men/category/jeans/brand/agadrianogoldschmied': np.int64(488),
 '/department/men/category/shorts/brand/burnside': np.int64(486),
 '/department/men/category/sleep&lounge/brand/funboxers': np.int64(482),
 '/department/women/category/sweaters/brand/suttonstudio': np.int64(479),
 '/department/women/category/sleep&lounge/brand/natori': np.int64(478),
 '/department/men/category/pants/brand/dickies': np.int64(478),
 '/department/women/category/fashionhoodies&sweatshirts/brand/activewearapparel': np.int64(477),
 '/department/men/category/sleep&lounge/brand/brieflystated': np.int64(477),
 '/department/women/category/socks&hosiery/brand/sockittome': np.int64(474),
 '/department/men/category/pants/brand/edgarments': np.int64(473),
 '/department/men/category/underwear/brand/tommyhilfiger': np.int64(472),
 '/department/women/category/sleep&lounge/brand/up2datefashion': np.int64(472),
 '/department/women/category/sleep&lounge/brand/carolehochman': np.int64(471),
 '/department/men/category/sleep&lounge/brand/alexanderdelrossa': np.int64(470),
 '/department/men/category/jeans/brand/silverjeans': np.int64(469),
 '/department/women/category/maternity/brand/bellybandit': np.int64(465),
 '/department/women/category/intimates/brand/undermoments': np.int64(462),
 '/department/men/category/suits&sportcoats/brand/giorgiocerruti': np.int64(460),
 '/department/men/category/outerwear&coats/brand/dickies': np.int64(458),
 '/department/women/category/maternity/brand/allegrak': np.int64(457),
 '/department/men/category/active/brand/smartwool': np.int64(457),
 '/department/women/category/maternity/brand/ecoscapes': np.int64(457),
 '/department/women/category/fashionhoodies&sweatshirts/brand/lifeisgood': np.int64(453),
 '/department/men/category/fashionhoodies&sweatshirts/brand/footballfanatics': np.int64(453),
 '/department/men/category/socks/brand/calvinklein': np.int64(452),
 '/department/men/category/underwear/brand/papi': np.int64(452),
 '/department/women/category/suits/brand/tahari': np.int64(452),
 '/department/women/category/shorts/brand/volcom': np.int64(448),
 '/department/men/category/tops&tees/brand/wrangler': np.int64(446),
 '/department/men/category/pants/brand/ralphlauren': np.int64(446),
 '/department/women/category/outerwear&coats/brand/carhartt': np.int64(444),
 '/department/women/category/blazers&jackets/brand/anneklein': np.int64(443),
 '/department/men/category/jeans/brand/hudson': np.int64(442),
 '/department/men/category/socks/brand/wrightsock': np.int64(440),
 '/department/women/category/swim/brand/clorismurphy': np.int64(439),
 '/department/women/category/leggings/brand/yelete': np.int64(437),
 '/department/women/category/dresses/brand/jonesnewyork': np.int64(434),
 "/department/men/category/outerwear&coats/brand/arc'teryx": np.int64(432),
 '/department/men/category/active/brand/exofficio': np.int64(430),
 '/department/women/category/active/brand/capezio': np.int64(430),
 '/department/men/category/active/brand/thorlo': np.int64(427),
 '/department/men/category/fashionhoodies&sweatshirts/brand/alpinestars': np.int64(425),
 '/department/women/category/intimates/brand/betseyjohnson': np.int64(425),
 '/department/women/category/fashionhoodies&sweatshirts/brand/americanapparel': np.int64(425),
 '/department/women/category/dresses/brand/kamalikulture': np.int64(422),
 '/department/men/category/tops&tees/brand/quiksilver': np.int64(421),
 '/department/men/category/jeans/brand/rockrevival': np.int64(421),
 '/department/men/category/outerwear&coats/brand/londonfog': np.int64(420),
 '/department/women/category/intimates/brand/corsetstory': np.int64(420),
 '/department/women/category/dresses/brand/patty': np.int64(420),
 '/department/men/category/active/brand/puma': np.int64(419),
 '/department/women/category/accessories/brand/oakley': np.int64(418),
 '/department/men/category/shorts/brand/volcom': np.int64(417),
 '/department/women/category/shorts/brand/hurley': np.int64(417),
 '/department/men/category/active/brand/underarmour': np.int64(416),
 '/department/men/category/swim/brand/nautica': np.int64(415),
 '/department/men/category/underwear/brand/gregghomme': np.int64(414),
 '/department/men/category/swim/brand/oakley': np.int64(414),
 '/department/women/category/leggings/brand/finebrandshop': np.int64(409),
 '/department/men/category/sweaters/brand/pendleton': np.int64(406),
 '/department/men/category/sleep&lounge/brand/edhardy': np.int64(406),
 '/department/men/category/underwear/brand/edhardy': np.int64(406),
 '/department/men/category/outerwear&coats/brand/woolrich': np.int64(404),
 '/department/men/category/swim/brand/fox': np.int64(402),
 '/department/women/category/shorts/brand/finebrandshop': np.int64(402),
 '/department/women/category/dresses/brand/bcbgmaxazria': np.int64(402),
 '/department/men/category/sweaters/brand/portauthority': np.int64(400),
 '/department/women/category/blazers&jackets/brand/jonesnewyork': np.int64(400),
 '/department/women/category/outerwear&coats/brand/calvinklein': np.int64(400),
 '/department/women/category/intimates/brand/comfortchoice': np.int64(397),
 '/department/women/category/plus/brand/bali': np.int64(396),
 '/department/men/category/swim/brand/tyr': np.int64(394),
 '/department/men/category/underwear/brand/dockers': np.int64(394),
 '/department/women/category/leggings/brand/stellaelyse': np.int64(391),
 '/department/women/category/dresses/brand/anneklein': np.int64(390),

In [14]:
dict(events["uri"].value_counts().head(100))

{'/cart': np.int64(592374),
 '/purchase': np.int64(180862),
 '/cancel': np.int64(124801),
 '/home': np.int64(87406),
 '/department/women/category/maternity/brand/motherhoodmaternity': np.int64(3341),
 '/department/women/category/blazers&jackets/brand/allegrak': np.int64(2836),
 '/department/men/category/jeans/brand/wrangler': np.int64(2739),
 '/department/men/category/swim/brand/quiksilver': np.int64(2334),
 '/department/women/category/dresses/brand/allegrak': np.int64(2269),
 "/department/women/category/jeans/brand/levi's": np.int64(2225),
 '/department/men/category/underwear/brand/calvinklein': np.int64(2186),
 '/department/men/category/pants/brand/dockers': np.int64(2174),
 '/department/men/category/underwear/brand/hanes': np.int64(2171),
 '/department/women/category/swim/brand/speedo': np.int64(2061),
 '/department/men/category/outerwear&coats/brand/carhartt': np.int64(2058),
 '/department/men/category/swim/brand/speedo': np.int64(1977),
 '/department/men/category/pants/brand/allegrak': np.int64(1953),
 '/department/men/category/jeans/brand/7forallmankind': np.int64(1920),
 '/department/women/category/tops&tees/brand/allegrak': np.int64(1758),
 '/department/men/category/jeans/brand/diesel': np.int64(1550),
 "/department/men/category/swim/brand/o'neill": np.int64(1518),
 "/department/women/category/jeans/brand/notyourdaughter'sjeans": np.int64(1447),
 '/department/men/category/sleep&lounge/brand/nautica': np.int64(1431),
 '/department/men/category/underwear/brand/fruitoftheloom': np.int64(1396),
 '/department/men/category/active/brand/champion': np.int64(1382),
 '/department/women/category/fashionhoodies&sweatshirts/brand/allegrak': np.int64(1369),
 '/department/women/category/intimates/brand/bali': np.int64(1357),
 '/department/men/category/pants/brand/haggar': np.int64(1355),
 '/department/women/category/intimates/brand/hanes': np.int64(1321),
 "/department/men/category/jeans/brand/joe'sjeans": np.int64(1312),
 '/department/women/category/shorts/brand/allegrak': np.int64(1311),
 '/department/women/category/intimates/brand/maidenform': np.int64(1303),
 '/department/men/category/accessories/brand/ray-ban': np.int64(1299),
 '/department/men/category/sleep&lounge/brand/majesticinternational': np.int64(1276),
 '/department/men/category/sleep&lounge/brand/hugoboss': np.int64(1270),
 '/department/women/category/jumpsuits&rompers/brand/allegrak': np.int64(1254),
 '/department/men/category/active/brand/adidas': np.int64(1250),
 '/department/men/category/underwear/brand/jockey': np.int64(1193),
 '/department/men/category/shorts/brand/quiksilver': np.int64(1157),
 '/department/men/category/underwear/brand/diesel': np.int64(1152),
 '/department/women/category/jeans/brand/7forallmankind': np.int64(1135),
 '/department/men/category/jeans/brand/truereligion': np.int64(1132),
 '/department/men/category/outerwear&coats/brand/columbia': np.int64(1115),
 '/department/men/category/suits&sportcoats/brand/allegrak': np.int64(1111),
 '/department/women/category/intimates/brand/laura': np.int64(1105),
 '/department/men/category/tops&tees/brand/carhartt': np.int64(1104),
 '/department/women/category/active/brand/champion': np.int64(1076),
 '/department/men/category/shorts/brand/hurley': np.int64(1049),
 '/department/men/category/jeans/brand/luckybrand': np.int64(1047),
 '/department/men/category/fashionhoodies&sweatshirts/brand/allegrak': np.int64(1019),
 '/department/women/category/intimates/brand/sexnight': np.int64(1017),
 '/department/men/category/swim/brand/garymajdellsport': np.int64(1016),
 '/department/men/category/accessories/brand/oakley': np.int64(987),
 '/department/men/category/sweaters/brand/calvinklein': np.int64(983),
 '/department/men/category/underwear/brand/2(x)ist': np.int64(979),
 '/department/women/category/intimates/brand/vanityfair': np.int64(968),
 '/department/men/category/swim/brand/hurley': np.int64(953),
 '/department/women/category/intimates/brand/ilusion': np.int64(942),
 '/department/women/category/socks&hosiery/brand/hue': np.int64(936),
 '/department/men/category/underwear/brand/c-in2': np.int64(927),
 '/department/women/category/accessories/brand/ray-ban': np.int64(925),
 "/department/men/category/sweaters/brand/thelittlealpaca'shouse": np.int64(916),
 '/department/women/category/dresses/brand/hotfromhollywood': np.int64(911),
 '/department/women/category/intimates/brand/wacoal': np.int64(908),
 '/department/women/category/maternity/brand/apeainthepod': np.int64(900),
 '/department/women/category/intimates/brand/calvinklein': np.int64(893),
 '/department/men/category/underwear/brand/duofold': np.int64(875),
 '/department/men/category/underwear/brand/hugoboss': np.int64(875),
 '/department/women/category/tops&tees/brand/patty': np.int64(873),
 '/department/women/category/maternity/brand/threeseasonsmaternity': np.int64(872),
 '/department/men/category/shorts/brand/dickies': np.int64(866),
 '/department/men/category/suits&sportcoats/brand/kingformalwear': np.int64(866),
 '/department/men/category/sleep&lounge/brand/bottomsout': np.int64(865),
 '/department/men/category/pants/brand/savane': np.int64(861),
 '/department/men/category/socks/brand/goldtoe': np.int64(855),
 '/department/men/category/sweaters/brand/tommyhilfiger': np.int64(846),
 '/department/women/category/leggings/brand/allegrak': np.int64(843),
 '/department/men/category/fashionhoodies&sweatshirts/brand/dc': np.int64(840),
 '/department/women/category/active/brand/adidas': np.int64(831),
 '/department/women/category/fashionhoodies&sweatshirts/brand/roxy': np.int64(825),
 '/department/women/category/intimates/brand/bslingerie': np.int64(821),
 "/department/men/category/jeans/brand/levi's": np.int64(810),
 '/department/men/category/suits&sportcoats/brand/tommyhilfiger': np.int64(806),
 '/department/men/category/tops&tees/brand/volcom': np.int64(805),
 '/department/men/category/swim/brand/volcom': np.int64(795),
 '/department/men/category/socks/brand/smartwool': np.int64(792),
 '/department/men/category/fashionhoodies&sweatshirts/brand/fox': np.int64(784),
 '/department/men/category/sweaters/brand/allegrak': np.int64(761),
 '/department/men/category/swim/brand/billabong': np.int64(758),
 '/department/men/category/sleep&lounge/brand/americanessentials': np.int64(754),
 "/department/women/category/intimates/brand/frederick'sofhollywood": np.int64(746),
 '/department/women/category/intimates/brand/flexees': np.int64(744),
 '/department/men/category/socks/brand/thorlo': np.int64(742),
 '/department/men/category/fashionhoodies&sweatshirts/brand/quiksilver': np.int64(740),
 '/department/men/category/active/brand/carhartt': np.int64(739),
 '/department/men/category/tops&tees/brand/u.s.poloassn.': np.int64(739),
 '/department/men/category/socks/brand/hanes': np.int64(735),
 '/department/men/category/sleep&lounge/brand/tommybahama': np.int64(733),
 '/department/men/category/tops&tees/brand/vanheusen': np.int64(730),
 '/department/men/category/socks/brand/wigwam': np.int64(727)}

In [15]:
events['uri'].nunique()

35530

In [16]:
events['page_type'] = events['uri'].str.extract(r'^/([^/]+)')
events['department'] = events['uri'].str.extract(r'/department/([^/]+)')
events['category'] = events['uri'].str.extract(r'/category/([^/]+)')
events['brand'] = events['uri'].str.extract(r'/brand/([^/]+)')

In [17]:
events[10000:20000]

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type,page_type,department,category,brand
10000,83811,6308,1,926270ec-9b61-4aa8-ad87-cf63855e7c42,2023-07-28 04:44:39+00:00,172.132.79.113,Jingzhou,Zhejiang,317200,Chrome,Email,/department/women/category/accessories/brand/t...,department,department,women,accessories,tomford
10001,153027,11688,4,8325ea73-5087-43ad-bc8a-a681a3dc6e5a,2023-07-14 09:18:18+00:00,194.32.45.87,Yichun,Zhejiang,317525,Firefox,Facebook,/department/men/category/jeans/brand/diesel,department,department,men,jeans,diesel
10002,1249598,96272,2,dbdd5264-ea7c-4aab-ab86-e73e7d97aa76,2023-03-09 14:02:33+00:00,77.177.51.232,Yichun,Zhejiang,317525,Firefox,Adwords,/department/men/category/active/brand/darntough,department,department,men,active,darntough
10003,1354691,<NA>,1,6b715535-17ac-4b7e-b541-863edbe38036,2019-10-29 03:46:00+00:00,56.63.206.184,Yichun,Zhejiang,317525,Chrome,Email,/department/women/category/shorts/brand/hurley,department,department,women,shorts,hurley
10004,875260,67259,4,55adbb1a-8c7d-4514-bd43-90d22a367ee6,2021-10-07 14:15:10+00:00,15.195.251.240,Yichun,Zhejiang,317525,Chrome,Adwords,/department/women/category/blazers&jackets/bra...,department,department,women,blazers&jackets,mcginn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,807420,62009,2,969edd0b-58bb-4573-8671-5cdd215fa8dc,2024-02-15 00:08:29+00:00,190.252.40.0,Santa María del Águila,Andalucía,4710,Other,Email,/product/5172,product,product,NaN,NaN,NaN
19996,1885567,<NA>,1,74f4d5f5-ddea-489a-9b5c-aafb36c994a2,2023-09-10 12:23:00+00:00,206.210.252.234,Barra,Bahia,47100-000,Chrome,Email,/product/20340,product,product,NaN,NaN,NaN
19997,1791318,<NA>,1,fae026e1-8c50-47d1-8da2-37a698b9931f,2024-04-01 04:03:00+00:00,93.116.150.34,Huizhou,Henan,471003,Chrome,Email,/product/15712,product,product,NaN,NaN,NaN
19998,2137061,<NA>,2,37deb942-da2a-4d4a-ba32-55a68ab71624,2021-03-14 14:33:00+00:00,190.117.104.90,Huizhou,Henan,471003,Chrome,Facebook,/product/22738,product,product,NaN,NaN,NaN
19999,29265,2107,5,5e50576f-5dbc-46eb-b40a-49a469de5023,2019-12-15 03:59:55+00:00,1.92.188.82,Huizhou,Henan,471003,Chrome,YouTube,/product/20021,product,product,NaN,NaN,NaN

Drop một số cột không cần thiết cho analysis

In [18]:
events = events.drop(columns=['ip_address', 'postal_code', 'uri', 'page_type'])

In [19]:
events.columns

Index(['id', 'user_id', 'sequence_number', 'session_id', 'created_at', 'city',
       'state', 'browser', 'traffic_source', 'event_type', 'department',
       'category', 'brand'],
      dtype='str')

In [20]:
events.info()

<class 'pandas.DataFrame'>
RangeIndex: 2420661 entries, 0 to 2420660
Data columns (total 13 columns):
 #   Column           Dtype
---  ------           -----
 0   id               int64
 1   user_id          Int64
 2   sequence_number  int64
 3   session_id       str
 4   created_at       datetime64[us, UTC]
 5   city             str
 6   state            str
 7   browser          str
 8   traffic_source   str
 9   event_type       str
 10  department       str
 11  category         str
 12  brand            str
dtypes: Int64(1), datetime64[us, UTC](1), int64(2), str(9)
memory usage: 426.2 MB

- Data khá clean, các cột còn lại giữ nguyên

In [74]:
events_clean = events

In [75]:
events_clean.to_csv("data/events_clean.csv", index=False)

2. Bảng order_items

In [23]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 180862 entries, 0 to 180861
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 180862 non-null  int64
 1   order_id           180862 non-null  int64
 2   user_id            180862 non-null  int64
 3   product_id         180862 non-null  int64
 4   inventory_item_id  180862 non-null  int64
 5   status             180862 non-null  str
 6   created_at         180862 non-null  str
 7   shipped_at         117919 non-null  str
 8   delivered_at       63463 non-null   str
 9   returned_at        18041 non-null   str
 10  sale_price         180862 non-null  float64
dtypes: float64(1), int64(5), str(5)
memory usage: 25.1 MB

In [24]:
order_items['created_at'] = pd.to_datetime(order_items['created_at'], format='mixed', utc=True)
order_items['shipped_at'] = pd.to_datetime(order_items['shipped_at'], format='mixed', utc=True)
order_items['delivered_at'] = pd.to_datetime(order_items['delivered_at'], format='mixed', utc=True)
order_items['returned_at'] = pd.to_datetime(order_items['returned_at'], format='mixed', utc=True)

In [25]:
order_items.head()

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price
0,101104,69639,55545,14235,273075,Cancelled,2021-12-27 23:35:57+00:00,NaT,NaT,NaT,0.02
1,17970,12402,9819,14235,48492,Complete,2024-01-21 08:21:43+00:00,2024-01-19 18:09:00+00:00,2024-01-21 09:20:00+00:00,NaT,0.02
2,46481,32099,25651,14235,125372,Complete,2019-10-06 06:14:19+00:00,2019-10-03 13:08:00+00:00,2019-10-04 01:04:00+00:00,NaT,0.02
3,162654,112208,89828,14235,439099,Processing,2022-12-11 00:43:18+00:00,NaT,NaT,NaT,0.02
4,61938,42730,34156,14235,167190,Returned,2023-09-20 11:58:48+00:00,2023-09-23 14:58:00+00:00,2023-09-25 07:58:00+00:00,2023-09-28 00:40:00+00:00,0.02

In [26]:
order_items = order_items.drop(columns=['inventory_item_id'])

In [27]:
order_items.head()

,id,order_id,user_id,product_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price
0,101104,69639,55545,14235,Cancelled,2021-12-27 23:35:57+00:00,NaT,NaT,NaT,0.02
1,17970,12402,9819,14235,Complete,2024-01-21 08:21:43+00:00,2024-01-19 18:09:00+00:00,2024-01-21 09:20:00+00:00,NaT,0.02
2,46481,32099,25651,14235,Complete,2019-10-06 06:14:19+00:00,2019-10-03 13:08:00+00:00,2019-10-04 01:04:00+00:00,NaT,0.02
3,162654,112208,89828,14235,Processing,2022-12-11 00:43:18+00:00,NaT,NaT,NaT,0.02
4,61938,42730,34156,14235,Returned,2023-09-20 11:58:48+00:00,2023-09-23 14:58:00+00:00,2023-09-25 07:58:00+00:00,2023-09-28 00:40:00+00:00,0.02

In [28]:
order_items.isna().sum()

id                   0
order_id             0
user_id              0
product_id           0
status               0
created_at           0
shipped_at       62943
delivered_at    117399
returned_at     162821
sale_price           0
dtype: int64

In [29]:
order_items.duplicated().sum()

np.int64(0)

In [30]:
order_items['status'].unique()

<ArrowStringArray>
['Cancelled', 'Complete', 'Processing', 'Returned', 'Shipped']
Length: 5, dtype: str

In [31]:
order_items['sale_price'].describe()

count    180862.000000
mean         59.693776
std          66.880191
min           0.020000
25%          24.950001
50%          39.990002
75%          69.949997
max         999.000000
Name: sale_price, dtype: float64

In [32]:
# order_items.to_csv("data/order_items_clean.csv", index=False)

3. Bảng orders

In [33]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 124814 entries, 0 to 124813
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      124814 non-null  int64
 1   user_id       124814 non-null  int64
 2   status        124814 non-null  str
 3   gender        124814 non-null  str
 4   created_at    124814 non-null  str
 5   returned_at   12439 non-null   str
 6   shipped_at    81454 non-null   str
 7   delivered_at  43867 non-null   str
 8   num_of_item   124814 non-null  int64
dtypes: int64(3), str(6)
memory usage: 15.5 MB

In [34]:
orders['created_at'] = pd.to_datetime(orders['created_at'], format='mixed', utc=True)
orders['returned_at'] = pd.to_datetime(orders['returned_at'], format='mixed', utc=True)
orders['shipped_at'] = pd.to_datetime(orders['shipped_at'], format='mixed', utc=True)
orders['delivered_at'] = pd.to_datetime(orders['delivered_at'], format='mixed', utc=True)

In [35]:
orders.head()

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
0,7,8,Cancelled,F,2023-09-06 10:43:00+00:00,NaT,NaT,NaT,1
1,40,36,Cancelled,F,2023-07-08 04:49:00+00:00,NaT,NaT,NaT,2
2,43,37,Cancelled,F,2023-12-04 05:29:00+00:00,NaT,NaT,NaT,1
3,59,50,Cancelled,F,2022-03-21 08:06:00+00:00,NaT,NaT,NaT,1
4,77,63,Cancelled,F,2024-02-04 15:21:00+00:00,NaT,NaT,NaT,1

In [36]:
orders.isna().mean()

order_id        0.000000
user_id         0.000000
status          0.000000
gender          0.000000
created_at      0.000000
returned_at     0.900340
shipped_at      0.347397
delivered_at    0.648541
num_of_item     0.000000
dtype: float64

In [37]:
orders.duplicated().sum()

np.int64(0)

In [38]:
orders['gender'].unique()

<ArrowStringArray>
['F', 'M']
Length: 2, dtype: str

In [39]:
orders['status'].unique()

<ArrowStringArray>
['Cancelled', 'Complete', 'Processing', 'Returned', 'Shipped']
Length: 5, dtype: str

In [40]:
orders['num_of_item'].unique()

array([1, 2, 3, 4])

In [41]:
orders['num_of_item'].describe()

count    124814.000000
mean          1.449052
std           0.803314
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max           4.000000
Name: num_of_item, dtype: float64

In [42]:
# orders.to_csv("data/orders_clean.csv", index=False)

4. Bảng users

In [43]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              100000 non-null  int64
 1   first_name      100000 non-null  str
 2   last_name       100000 non-null  str
 3   email           100000 non-null  str
 4   age             100000 non-null  int64
 5   gender          100000 non-null  str
 6   state           100000 non-null  str
 7   street_address  100000 non-null  str
 8   postal_code     100000 non-null  str
 9   city            99045 non-null   str
 10  country         100000 non-null  str
 11  latitude        100000 non-null  float64
 12  longitude       100000 non-null  float64
 13  traffic_source  100000 non-null  str
 14  created_at      100000 non-null  str
dtypes: float64(2), int64(2), str(11)
memory usage: 23.0 MB

In [44]:
users['created_at'] = pd.to_datetime(users['created_at'], format='mixed', utc=True)

In [45]:
users.head()

,id,first_name,last_name,email,age,gender,state,street_address,postal_code,city,country,latitude,longitude,traffic_source,created_at
0,8142,Dean,Vance,deanvance@example.net,50,M,Acre,8821 Wolf Trail,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2022-10-30 17:46:00+00:00
1,24645,Michael,Turner,michaelturner@example.org,28,M,Acre,600 Monica Fort Apt. 260,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2022-08-08 13:16:00+00:00
2,34950,Shari,Medina,sharimedina@example.net,59,F,Acre,98922 Villarreal Brook,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2023-09-26 05:11:00+00:00
3,37723,Matthew,Dunn,matthewdunn@example.net,16,M,Acre,724 Michele Island Apt. 077,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2019-06-13 18:09:00+00:00
4,43283,Michael,Stevens,michaelstevens@example.net,70,M,Acre,220 Butler Lake Suite 506,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2023-07-24 14:57:00+00:00

In [46]:
users.columns

Index(['id', 'first_name', 'last_name', 'email', 'age', 'gender', 'state',
       'street_address', 'postal_code', 'city', 'country', 'latitude',
       'longitude', 'traffic_source', 'created_at'],
      dtype='str')

Drop các cột không cần thiết cho phân tích Traffic và Funnel

In [47]:
users = users.drop(columns=['first_name', 'last_name', 'email', 'street_address', 'postal_code', 'latitude', 'longitude'])

In [48]:
users.isna().sum()

id                  0
age                 0
gender              0
state               0
city              955
country             0
traffic_source      0
created_at          0
dtype: int64

- Cột city số lượng null nhỏ, nếu phân tích users theo địa lý sẽ chủ yếu dùng state, country thay vì city

In [49]:
users.duplicated().sum()

np.int64(0)

In [50]:
users.head()

,id,age,gender,state,city,country,traffic_source,created_at
0,8142,50,M,Acre,Rio Branco,Brasil,Search,2022-10-30 17:46:00+00:00
1,24645,28,M,Acre,Rio Branco,Brasil,Search,2022-08-08 13:16:00+00:00
2,34950,59,F,Acre,Rio Branco,Brasil,Search,2023-09-26 05:11:00+00:00
3,37723,16,M,Acre,Rio Branco,Brasil,Search,2019-06-13 18:09:00+00:00
4,43283,70,M,Acre,Rio Branco,Brasil,Search,2023-07-24 14:57:00+00:00

In [51]:
users['age'].describe()

count    100000.000000
mean         41.060310
std          17.067162
min          12.000000
25%          26.000000
50%          41.000000
75%          56.000000
max          70.000000
Name: age, dtype: float64

In [52]:
users['age'].unique()

array([50, 28, 59, 16, 70, 60, 48, 51, 63, 54, 37, 40, 43, 17, 38, 24, 34,
       20, 12, 56, 18, 55, 67, 64, 41, 35, 32, 42, 27, 68, 44, 46, 13, 29,
       15, 57, 36, 65, 62, 61, 22, 26, 25, 58, 52, 47, 69, 49, 14, 33, 23,
       45, 53, 66, 21, 31, 39, 19, 30])

In [53]:
users['gender'].value_counts()

gender
M    50148
F    49852
Name: count, dtype: int64

In [54]:
list(users['state'].unique())

['Acre',
 'Aichi',
 'Akita',
 'Alabama',
 'Alagoas',
 'Alaska',
 'Amapá',
 'Amazonas',
 'Andalucía',
 'Anhui',
 'Aomori',
 'Aragón',
 'Arizona',
 'Arkansas',
 'Australian Capital Territory',
 'Auvergne-Rhône-Alpes',
 'Baden-Württemberg',
 'Bagmati region',
 'Bahia',
 'Bayern',
 'Beijing',
 'Berlin',
 'Bourgogne-Franche-Comté',
 'Brandenburg',
 'Bremen',
 'Bretagne',
 'Brussels',
 'Busan',
 'California',
 'Canarias',
 'Cantabria',
 'Castilla y León',
 'Castilla-La Mancha',
 'Cataluña',
 'Ceará',
 'Centre-Val de Loire',
 'Ceuta',
 'Chiba',
 'Chongqing',
 'Chung-cheong bukdo',
 'Chungcheongnam-do',
 'Colorado',
 'Comunidad Valenciana',
 'Comunidad de Madrid',
 'Connecticut',
 'Corse',
 'Daegu Metropolitan City',
 'Daejeon',
 'Delaware',
 'District of Columbia',
 'Distrito Federal',
 'Dolnośląskie',
 'England',
 'Espírito Santo',
 'Extremadura',
 'Flanders',
 'Florida',
 'Fujian',
 'Fukuoka',
 'Fukushima',
 'Galicia',
 'Gangwon-do',
 'Gansu province',
 'Georgia',
 'Gifu',
 'Goiás',
 'Grand Est',
 'Guangdong',
 'Guangxi Zhuang Autonomous Region',
 'Guizhou',
 'Gunma',
 'Gwangju',
 'Gyeonggi-do',
 'Gyeongsangbuk-do',
 'Gyeongsangnam-do',
 'Hainan',
 'Hamburg',
 'Hauts-de-France',
 'Hawaii',
 'Hebei',
 'Heilongjiang',
 'Henan',
 'Hessen',
 'Hiroshima',
 'Hokkaido',
 'Hubei',
 'Hunan',
 'Hyogo',
 'Ibaraki',
 'Idaho',
 'Illinois',
 'Incheon Metropolitan City',
 'Indiana',
 'Inner Mongolia Autonomous Region',
 'Iowa',
 'Islas Baleares',
 'Iwate',
 'Jeju Special Self-Governing Province',
 'Jeollabuk do',
 'Jeollanam-do',
 'Jiangsu',
 'Jiangxi',
 'Jilin',
 'Kagawa',
 'Kagoshima',
 'Kanagawa',
 'Kansas',
 'Kentucky',
 'Kochi',
 'Kumamoto',
 'Kyoto',
 'La Rioja',
 'Liaoning',
 'Louisiana',
 'Lubuskie',
 'Maine',
 'Maranhão',
 'Maryland',
 'Massachusetts',
 'Mato Grosso',
 'Mato Grosso do Sul',
 'Mecklenburg-Vorpommern',
 'Melilla',
 'Michigan',
 'Minas Gerais',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Miyagi',
 'Miyazaki',
 'Montana',
 'Nagano',
 'Nagasaki',
 'Nara',
 'Navarra',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New South Wales',
 'New York',
 'Niedersachsen',
 'Ningxia Hui Autonomous Region',
 'Nordrhein-Westfalen',
 'Normandie',
 'North Carolina',
 'North Dakota',
 'Northern Ireland',
 'Northern Territory',
 'Nouvelle-Aquitaine',
 'Occitanie',
 'Ohio',
 'Oita',
 'Okayama',
 'Okinawa',
 'Oklahoma',
 'Oregon',
 'Osaka',
 'Paraná',
 'Paraíba',
 'Pará',
 'Pays de la Loire',
 'País Vasco',
 'Pennsylvania',
 'Pernambuco',
 'Piauí',
 'Principado de Asturias',
 "Provence-Alpes-Côte d'Azur",
 'Qinghai',
 'Queensland',
 'Región de Murcia',
 'Remote territory',
 'Rheinland-Pfalz',
 'Rhode Island',
 'Rio Grande do Norte',
 'Rio Grande do Sul',
 'Rio de Janeiro',
 'Rondônia',
 'Roraima',
 'Saarland',
 'Sachsen',
 'Sachsen-Anhalt',
 'Saitama',
 'Santa Catarina',
 'Schleswig-Holstein',
 'Scotland',
 'Seoul',
 'Sergipe',
 'Shaanxi',
 'Shandong',
 'Shanghai',
 'Shanxi',
 'Shiga',
 'Shizuoka',
 'Sichuan',
 'South Australia',
 'South Carolina',
 'South Dakota',
 'São Paulo',
 'Tasmania',
 'Tennessee',
 'Texas',
 'Thüringen',
 'Tianjin',
 'Tocantins',
 'Tochigi',
 'Tokyo',
 'Ulsan Metropolitan City',
 'Utah',
 'Vermont',
 'Victoria',
 'Virginia',
 'Wakayama',
 'Wales',
 'Wallonia',
 'Washington',
 'West Virginia',
 'Western Australia',
 'Wisconsin',
 'Wyoming',
 'Xinjiang Uygur Autonomous Region',
 'Yamaguchi',
 'Yunnan',
 'Zachodniopomorskie',
 'Zhejiang',
 'Île-de-France']

In [55]:
list(users['city'].unique())

['Rio Branco',
 'Sena Madureira',
 'Tarauacá',
 nan,
 'Ichinomiya City',
 'Tokai-shi',
 'North Nagoya City',
 'Chita City',
 'Nagoya city',
 'Toyuyama-cho',
 '桑',
 'Higashiura-cho',
 'Ofu City',
 'Small animal husbandry',
 'Kariya City',
 'Ming Ming',
 'Anjo city',
 'Togo-cho',
 'Daily enterprise',
 'Long time',
 'Miyoshi city',
 'Toyohashi City',
 'Loda City',
 'Dothan',
 'Auburn',
 'Enterprise',
 'Talladega',
 'Montgomery',
 'Huntsville',
 'Trussville',
 'Prattville',
 'Hoover',
 'Birmingham',
 'Madison',
 'Harvest',
 'Pelham',
 'Vestavia Hills',
 'Alabaster',
 'Homewood',
 'Hartselle',
 'Bessemer',
 'Decatur',
 'Athens',
 'Hueytown',
 'Tuscaloosa',
 'Florence',
 'Foley',
 'Daphne',
 'Fairhope',
 'Mobile',
 'Theodore',
 'São Luís do Quitunde',
 'Maceió',
 'Rio Largo',
 'Marechal Deodoro',
 'União dos Palmares',
 'Pilar',
 'Atalaia',
 'São Miguel dos Campos',
 'Coruripe',
 'Campo Alegre',
 'Teotônio Vilela',
 'Penedo',
 'Santana do Ipanema',
 'São José da Tapera',
 'Lagoinha',
 'Juneau',
 'Eielson Air Force Base',
 'Ester',
 'Anchorage',
 'Knik River',
 'Point MacKenzie',
 'Macapá',
 'Santana',
 'Itacoatiara',
 'Autazes',
 'Rio Preto da Eva',
 'Manaus',
 'Iranduba',
 'Colônia Boa Vista',
 'Tefé',
 'São Gabriel da Cachoeira',
 'Tabatinga',
 'Camilo Torres',
 'Guajará',
 'Huércal-Overa',
 'San Isidro de Níjar',
 'Campohermoso',
 'Cuevas de los Medinas',
 'La Cañada',
 'Almería',
 'Huércal de Almería',
 'Aguadulce',
 'Huéscar',
 'Roquetas de Mar',
 'La Gangosa',
 'Santa María del Águila',
 'Baza',
 'El Ejido',
 'Guardias Viejas',
 'Villacarrillo',
 'Adra',
 'Úbeda',
 'Motril',
 'Baeza',
 'El Varadero',
 'Granada',
 'Huétor Vega',
 'La Zubia',
 'Salobreña',
 'Pulianas',
 'Ogíjares',
 'La Carolina',
 'Peligros',
 'Maracena',
 'Linares',
 'Albolote',
 'Padul',
 'Las Gabias',
 'Alhendín',
 'La Guardia de Jaén',
 'Atarfe',
 'Velilla-Taramay',
 'Las Infantas',
 'Santa Fe',
 'Jaén',
 'Bailén',
 'Mengíbar',
 'Nerja',
 'Martos',
 'Andújar',
 'Huétor Tájar',
 'Alcaudete',
 'Loja',
 'Priego de Córdoba',
 'Rincón de la Victoria',
 'Baena',
 'Málaga',
 'Montoro',
 'Córdoba',
 'Cabra',
 'Torremolinos',
 'Lucena',
 'Benalmádena',
 'Antequera',
 'Alhaurín de la Torre',
 'Fuengirola',
 'Estación de Cártama',
 'Montilla',
 'Mijas',
 'Cártama',
 'Las Lagunas de Mijas',
 'Aguilar de la Frontera',
 'Alhaurín el Grande',
 'Calahonda',
 'Majaneque',
 'Puente Genil',
 'Coín',
 'Marbella',
 'La Rambla',
 'Pozoblanco',
 'Estepa',
 'El Paraíso',
 'Cañada del Rabadán',
 'Écija',
 'Osuna',
 'Ronda',
 'Estepona',
 'Palma del Río',
 'Peñarroya-Pueblonuevo',
 'La Puebla de Cazalla',
 'Olvera',
 'San Roque',
 'La Línea de la Concepción',
 'Marchena',
 'Morón de la Frontera',
 'Algeciras',
 'Palmones',
 'Ubrique',
 'Lora del Río',
 'Montellano',
 'Arahal',
 'Carmona',
 'Arcos de la Frontera',
 'Mairena del Alcor',
 'Utrera',
 'Alcalá de Guadaíra',
 'Barbate',
 'Sevilla',
 'Dos Hermanas',
 'Los Palacios y Villafranca',
 'Medina-Sidonia',
 'Las Cabezas de San Juan',
 'San José de la Rinconada',
 'Montequinto',
 'Vejer de la Frontera',
 'Nueva Jarilla',
 'Alcalá del Río',
 'San Juan de Aznalfarache',
 'Santiponce',
 'Camas',
 'Tomares',
 'Coria del Río',
 'Gelves',
 'Castilleja de la Cuesta',
 'Palomares del Río',
 'Lebrija',
 'Mairena del Aljarafe',
 'Valencina de la Concepción',
 'Conil de la Frontera',
 'Gines',
 'Bormujos',
 'Guillena',
 'Puerto Real',
 'Chiclana de la Frontera',
 'Jerez de la Frontera',
 'Espartinas',
 'Bollullos de la Mitación',
 'Olivares',
 'San Fernando',
 'El Trocadero',
 'El Puerto de Santa María',
 'Sanlúcar la Mayor',
 'Cádiz',
 'Sanlúcar de Barrameda',
 'Pilas',
 'Chipiona',
 'Almonte',
 'Bollullos Par del Condado',
 'Valverde del Camino',
 'Moguer',
 'Trigueros',
 'Palos de la Frontera',
 'Huelva',
 'Gibraleón',
 'Punta Umbría',
 'Aljaraque',
 'Cartaya',
 'Lepe',
 'Isla Cristina',
 'Bengbu',
 'Hangzhou',
 'Beijing',
 'Shan Tou',
 'Shanghai',
 'Zhengzhou',
 'Harbin',
 'Zhangjiakou',
 'Enshi Tujia Miao Autonomous Prefecture',
 'Jinan',
 'Wuhan',
 'Southwestern Buyi Miao Autonomous Prefecture',
 'Changsha',
 'Shenzhen',
 'Xiamen',
 'Nanyang',
 'Taiyuan',
 'Guiyang',
 'Guangzhou',
 'Huainan',
 'Chongqing',
 'Baiyin',
 'Taizhou',
 'Nanjing',
 'Jinzhou',
 'Pingliang',
 'Zhuzhou',
 'Chengdu',
 'Anyang',
 'Aomori City',
 'Misawa City',
 'Hachinohe',
 'Barbastro',
 'Monzón',
 'Fraga',
 'Caspe',
 'Alcañiz',
 'Huesca',
 'Cuarte',
 'Jaca',
 'Cartuja Baja',
 'Movera',
 'Zaragoza',
 'Utebo',
 'Garrapinillos',
 'Ejea de los Caballeros',
 'La Almunia de Doña Godina',
 'Tarazona',
 'Douglas',
 'Sierra Vista',
 'Tucson',
 'Catalina Foothills',
 'Catalina',
 'Casas Adobes',
 'Sahuarita',
 'Drexel Heights',
 'Nogales',
 'Marana',
 'Picture Rocks',
 'Apache Junction',
 'Gold Canyon',
 'Flagstaff',
 'San Tan Valley',
 'Coolidge',
 'Mesa',
 'Queen Creek',
 'Gilbert',
 'Fountain Hills',
 'Casa Grande',
 'Scottsdale',
 'Chandler',
 'Tempe',
 'Cave Creek',
 'Phoenix',
 'Maricopa',
 'Cottonwood',
 'New River',
 'Ak-Chin Indian Community',
 'Glendale',
 'Peoria',
 'Sun City',
 'Avondale',
 'Prescott Valley',
 'El Mirage',
 'Sun City West',
 'Surprise',
 'Goodyear',
 'Buckeye',
 'Prescott',
 'Kingman',
 'New Kingman-Butler',
 'Lake Havasu City',
 'Yuma',
 'Fortuna Foothills',
 'Bullhead City',
 'San Luis',
 'Paragould',
 'Jonesboro',
 'Batesville',
 'Searcy',
 'Cabot',
 'Pine Bluff',
 'Jacksonville',
 'Little Rock',
 'Sherwood',
 'Conway',
 'Mountain Home',
 'Benton',
 'El Dorado',
 'Malvern',
 'Hot Springs',
 'Russellville',
 'Harrison',
 'Texarkana',
 'Rogers',
 'Fayetteville',
 'Springdale',
 'Bentonville',
 'Van Buren',
 'Fort Smith',
 'Canberra',
 'Aurillac',
 'Arpajon-sur-Cère',
 'Montluçon',
 'Clermont-Ferrand',
 'Riom',
 'Aubière',
 'Gerzat',
 "Cournon-d'Auvergne",
 'Pont-du-Château',
 'Issoire',
 'Bressolles',
 'Yzeure',
 'Lezoux',
 'Abrest',
 'Cusset',
 'Polignac',
 'Saint-Germain-Laprade',
 'Saint-Étienne-le-Molard',
 'Mably',
 'Roche',
 'Perreux',
 'Yssingeaux',
 'Saint-Maurice-en-Gourgois',
 'Sainte-Foy-Saint-Sulpice',
 'Saint-Just-Saint-Rambert',
 'Saint-Cyr-les-Vignes',
 'Andrézieux-Bouthéon',
 'Firminy',
 'Saint-Étienne',
 'Saint-Galmier',
 'Rochecolombe',
 'Joux',
 'Saint-Chamond',
 "Val d'Oingt",
 'Gras',
 'Pranles',
 'Saint-Romain-en-Jarez',
 'Savigny',
 'Alba-la-Romaine',
 'Chabanière',
 'Thurins',
 'Annonay',
 'Pollionnay',
 'Arnas',
 'Chasselay',
 'Anse',
 'Pierrelatte',
 'Belleville-en-Beaujolais',
 'Orliénas',
 'Beauvallon',
 'Peaugres',
 'Montélimar',
 'Tassin-la-Demi-Lune',
 'Écully',
 'Tournon-sur-Rhône',
 'Millery',
 'Saint-Genis-Laval',
 "Saint-Maurice-l'Exil",
 'Lyon',
 'Oullins',
 'Reyrieux',
 'Villeneuve',
 "Saint-Symphorien-d'Ozon",
 'Saint-Fons',
 'Caluire-et-Cuire',
 'Cailloux-sur-Fontaines',
 'Anneyron',
 'Ville-sous-Anjou',
 'Vénissieux',
 'Villeurbanne',
 'Étoile-sur-Rhône',
 'Bourg-lès-Valence',
 'Rillieux-la-Pape',
 'Vienne',
 'Bron',
 'Valence',
 'Vaulx-en-Velin',
 'Saint-Priest',
 'Miribel',
 'Décines-Charpieu',
 'Eyzin-Pinet',
 'Saint-Pierre-de-Chandieu',
 'Genas',
 'Primarette',
 'Chabeuil',
 'Romans-sur-Isère',
 'Meyzieu',
 'Grane',
 'Châteauneuf-sur-Isère',
 'Foissiat',
 'Chatonnay',
 'Saint-Maurice-de-Gourdans',
 'Tignieu-Jameyzieu',
 'Vinsobres',
 'Porte-des-Bonnevaux',
 'Saint-Marcel-Bel-Accueil',
 'Bourg-en-Bresse',
 'Trept',
 'Bourgoin-Jallieu',
 "Saint-Antoine-l'Abbaye",
 'Lagnieu',
 'Ambronay',
 'Nivigne et Suran',
 'Châbons',
 'Varacieux',
 'Saint-Didier-de-la-Tour',
 'Courtenay',
 'Izeaux',
 'Tullins',
 'Les Abrets en Dauphiné',
 'Voiron',
 'Engins',
 'Oyonnax',
 'Le Gua',
 'Arboys-en-Bugey',
 'Seyssinet-Pariset',
 'Fontaine',
 'Proveysieux',
 'Champagnier',
 'Échirolles',
 'Grenoble',
 'Le Sappey-en-Chartreuse',
 'Brié-et-Angonnes',
 'Meylan',
 'Valserhône',
 'Saint-Ismier',
 'Livet-et-Gavet',
 'Revel',
 'Chambéry',
 'Plateau-des-Petites-Roches',
 'Desingy',
 'Saint-Offenge',
 'Moye',
 'Péron',
 'Chapareillan',
 'Gex',
 'Cusy',
 'Choisy',
 'Porte-de-Savoie',
 'Annecy',
 'Versonnex',
 'Archamps',
 'Cruseilles',
 'Fillière',
 'Vétraz-Monthoux',
 'Reignier-Esery',
 'Faverges',
 'Cranves-Sales',
 'La Roche-sur-Foron',
 'Sciez',
 'Mercury',
 'Viuz-en-Sallaz',
 'Glières-Val-de-Borne',
 'Thonon-les-Bains',
 'Sallanches',
 'Magland',
 'Bernex',
 'Bourg-Saint-Maurice',
 'Weil am Rhein',
 'Müllheim',
 'Lörrach',
 'Freiburg im Breisgau',
 'Rheinfelden (Baden)',
 'Kehl',
 'Emmendingen',
 'Schopfheim',
 'Lahr/Schwarzwald',
 'Offenburg',
 'Bad Säckingen',
 'Waldkirch',
 'Achern',
 'Oberkirch',
 'Bühl',
 'Rastatt',
 'Baden-Baden',
 'Waldshut-Tiengen',
 'Rheinstetten',
 'Karlsruhe',
 'Ettlingen',
 'Freudenstadt',
 'Villingen-Schwenningen',
 'Mannheim',
 'Stutensee',
 'Donaueschingen',
 'Hockenheim',
 'Waghäusel',
 'Pfinztal',
 'Schwetzingen',
 'Heidelberg',
 'Rottweil',
 'Horb am Neckar',
 'Weinheim',
 'Bretten',
 'Pforzheim',
 'Wiesloch',
 'Nagold',
 'Calw',
 'Tuttlingen',
 'Mühlacker',
 'Balingen',
 'Weil der Stadt',
 'Herrenberg',
 'Singen (Hohentwiel)',
 'Sinsheim',
 'Rottenburg am Neckar',
 'Eppingen',
 'Vaihingen an der Enz',
 'Böblingen',
 'Radolfzell am Bodensee',
 'Sachsenheim',
 'Leonberg',
 'Ditzingen',
 'Tübingen',
 'Sindelfingen',
 'Gerlingen',
 'Bad Rappenau',
 'Mössingen',
 'Stuttgart',
 'Korntal-Münchingen',
 'Bietigheim-Bissingen',
 'Heilbronn',
 'Leinfelden-Echterdingen',
 'Konstanz',
 'Reutlingen',
 'Überlingen',
 'Ludwigsburg',
 'Kornwestheim',
 'Filderstadt',
 'Bad Friedrichshall',
 'Neckarsulm',
 'Ostfildern',
 'Remseck am Neckar',
 'Fellbach',
 'Steinheim an der Murr',
 'Esslingen am Neckar',
 'Metzingen',
 'Waiblingen',
 'Nürtingen',
 'Weinstadt',
 'Winnenden',
 'Backnang',
 'Kirchheim unter Teck',
 'Friedrichshafen',
 'Öhringen',
 'Wertheim',
 'Schorndorf',
 'Ravensburg',
 'Tettnang',
 'Göppingen',
 'Weingarten',
 'Künzelsau',
 'Eislingen/Fils',
 'Bad Waldsee',
 'Schwäbisch Hall',
 'Bad Mergentheim',
 'Wangen im Allgäu',
 'Schwäbisch Gmünd',
 'Geislingen an der Steige',
 'Laupheim',
 'Ulm',
 'Leutkirch im Allgäu',
 'Crailsheim',
 'Heidenheim an der Brenz',
 'Esplanada',
 'Rio Real',
 'Entre Rios',
 'Mata de São João',
 'Pojuca',
 "Dias d'Ávila",
 'Camaçari',
 'Lauro de Freitas',
 'Salvador',
 'Simões Filho',
 'Inhambupe',
 'Cícero Dantas',
 'Catu',
 'Ribeira do Pombal',
 'Lamarão do Passé',
 'Jeremoabo',
 'São Francisco do Conde',
 'Vera Cruz',
 'Conceição do Jacuípe',
 'Santo Amaro',
 'Euclides da Cunha',
 'Murutuba',
 'São Roque do Paraguaçu',
 'Serrinha',
 'Cruz das Almas',
 'Camamu',
 'Valença',
 'Conceição do Coité',
 'Santo Estêvão',
 'Porto Seguro',
 'Riachão do Jacuípe',
 'Monte Santo',
 'Santaluz',
 'Eunápolis',
 'Amargosa',
 'Nova Viçosa',
 'Teixeira de Freitas',
 'Ipiaú',
 'Itamaraju',
 'Ipirá',
 'Itiúba',
 'Mucuri',
 'Jaguaquara',
 'Itapetinga',
 'Jaguarari',
 'Senhor do Bonfim',
 'Itaberaba',
 'Poções',
 'Jacobina',
 'Campo Formoso',
 'Morro do Chapéu',
 'Casa Nova',
 'Brumado',
 'Irecê',
 'Seabra',
 'Livramento de Nossa Senhora',
 'Remanso',
 'Caetité',
 'Macaúbas',
 'Xique-Xique',
 'Guanambi',
 'Bom Jesus da Lapa',
 'Barra',
 'Santa Maria da Vitória',
 'São Desidério',
 'Luis Eduardo Magalhães',
 'Alzenau',
 'Aschaffenburg',
 'Lindau (Bodensee)',
 'Würzburg',
 'Neu-Ulm',
 'Senden',
 'Kitzingen',
 'Memmingen',
 'Schweinfurt',
 'Kempten (Allgäu)',
 'Günzburg',
 'Sonthofen',
 'Nördlingen',
 'Dillingen an der Donau',
 'Ansbach',
 'Marktoberdorf',
 'Kaufbeuren',
 'Donauwörth',
 'Neusäß',
 'Gersthofen',
 'Augsburg',
 'Landsberg am Lech',
 'Bamberg',
 'Königsbrunn',
 'Zirndorf',
 'Fürth',
 'Erlangen',
 'Coburg',
 'Schwabach',
 'Friedberg',
 'Nürnberg',
 'Forchheim',
 'Garmisch-Partenkirchen',
 'Lichtenfels',
 'Roth',
 'Aichach',
 'Erlenstegener Forst',
 'Weilheim in Oberbayern',
 'Wendelstein',
 'Neuburg an der Donau',
 'Fürstenfeldbruck',
 'Fischbach',
 'Lauf an der Pegnitz',
 'Starnberg',
 'Ingolstadt',
 'Puchheim',
 'Olching',
 'Gauting',
 'Germering',
 'Krailling',
 'München',
 'Kulmbach',
 'Gräfelfing',
 'Dachau',
 'Geretsried',
 'Karlsfeld',
 'Neumarkt in der Oberpfalz',
 'Pfaffenhofen an der Ilm',
 'Wackersberg',
 'Bayreuth',
 'Unterschleißheim',
 'Oberhaching',
 'Unterhaching',
 'Garching bei München',
 'Neubiberg',
 'Ottobrunn',
 'Freising',
 'Haar',
 'Sulzbach-Rosenberg',
 'Amberg',
 'Erding',
 'Moosburg an der Isar',
 'Bad Aibling',
 'Schwandorf',
 'Altdorf',
 'Regensburg',
 'Rosenheim',
 'Ergolding',
 'Weiden in der Oberpfalz',
 'Kumhausen',
 'Waldkraiburg',
 'Straubing',
 'Traunstein',
 'Freilassing',
 'Deggendorf',
 'Passau',
 'Shiyan',
 'Qingdao',
 'Nanchang',
 'Loudi',
 'Xingtai',
 'NanNing',
 'Xuancheng',
 'Luoyang',
 'Yingkou',
 'Huaian',
 'Zhangzhou',
 'Bayannre',
 'Urumqi',
 'Handan',
 'Dongguan',
 'Dandong',
 'Jinzhong',
 'Zhongshan',
 'Huaihua',
 'Suzhou',
 'Chaoyang',
 'Wenzhou',
 'Linxia Hui Autonomous Prefecture',
 'Pingxiang',
 'Zhumadian',
 'Qujing',
 'Yiyang',
 'Chizhou',
 'Foshan',
 'Ziyang',
 'Hami',
 "Lan'Zhou",
 'Zhongwei',
 'Huanggang',
 'Luliang',
 'Hengshui',
 'Lijiang',
 'Weihai',
 'Changzhi',
 'Tieling',
 'Shaoxing',
 'Anqing',
 'Huaibei',
 'Huludao',
 'Baoding',
 'Berlin',
 'Sermoise-sur-Loire',
 'Villethierry',
 'Malay-le-Grand',
 'Joigny',
 'Bussy-en-Othe',
 'Auxerre',
 'Poisson',
 'Autun',
 'Saint-Berain-sous-Sanvignes',
 'Le Creusot',
 'Saint-Eusèbe',
 'Mâcon',
 'Chalon-sur-Saône',
 'Sennecey-le-Grand',
 'Sassenay',
 'Beaune',
 'Allériot',
 'Argilly',
 'Dijon',
 'Marey-sur-Tille',
 'Chevigny-Saint-Sauveur',
 'Izeure',
 'Saint-Usuge',
 'Auxonne',
 'Dole',
 'Lons-le-Saunier',
 'Hauteroche',
 'Beaujeu-Saint-Vallier-Pierrejux-et-Quitteur',
 'Montrond',
 'Besançon',
 'Les Auxons',
 'Rioz',
 'Noroy-le-Bourg',
 'Pontarlier',
 'Lure',
 'Montlebon',
 'Saulnot',
 'Mathay',
 'Montbéliard',
 'Lachapelle-Sous-Chaux',
 'Belfort',
 'Audincourt',
 'Florimont',
 'Wittenberge',
 'Rathenow',
 'Wittstock/Dosse',
 'Brandenburg an der Havel',
 'Neuruppin',
 'Nauen',
 'Werder (Havel)',
 'Potsdam',
 'Falkensee',
 'Niedergörsdorf',
 'Oberkrämer',
 'Löwenberger Land',
 'Luckenwalde',
 'Hennigsdorf',
 'Stahnsdorf',
 'Ludwigsfelde',
 'Teltow',
 'Oranienburg',
 'Schönefeld',
 'Panketal',
 'Bernau bei Berlin',
 'Templin',
 'Hoppegarten',
 'Werneuchen',
 'Finsterwalde',
 'Fredersdorf-Vogelsdorf',
 'Eberswalde',
 'Grünheide (Mark)',
 'Nordwestuckermark',
 'Strausberg',
 'Altlandsberg',
 'Senftenberg',
 'Bad Freienwalde (Oder)',
 'Fürstenwalde/Spree',
 'Rietz-Neuendorf',
 'Schwedt/Oder',
 'Cottbus',
 'Spremberg',
 'Frankfurt (Oder)',
 'Siehdichum',
 'Schenkendöbern',
 'Forst (Lausitz)',
 'Bremerhaven',
 'Bremen',
 'Saint-Germain-en-Coglès',
 'Vitré',
 'Fougères',
 'Rives-du-Couesnon',
 'Liffré',
 'Noyal-sur-Vilaine',
 'Janzé',
 'Châteaugiron',
 'Tresbœuf',
 "Saint-Aubin-d'Aubigné",
 'Noyal-Châtillon-sur-Seiche',
 'Rennes',
 'Saint-Grégoire',
 'Bain-de-Bretagne',
 'Mont-Dol',
 'Saint-Jacques-de-la-Lande',
 'Bruz',
 'Guignen',
 'Bréal-sous-Montfort',
 'Tinténiac',
 'Saint-Malo',
 'Montauban-de-Bretagne',
 'Taden',
 'Bains-sur-Oust',
 'Corseul',
 'Caro',
 'Campénéac',
 'Questembert',
 'Noyal-Muzillac',
 'Elven',
 "Plœuc-L'Hermitage",
 'Vannes',
 'Loudéac',
 'Saint-Brieuc',
 'Plérin',
 'Saint-Avé',
 'Ploufragan',
 'Évellys',
 'Grand-Champ',
 'Le Vieux-Bourg',
 'Plumergat',
 'Plélo',
 'Malguénac',
 'Kervignac',
 'Lanester',
 'Lorient',
 'Ploemeur',
 'Lannion',
 'Arzano',
 'Cléden-Poher',
 'Plourin-lès-Morlaix',
 'Rosporden',
 'Concarneau',
 'Fouesnant',
 'Quimper',
 'Plounéventer',
 'Ploudiry',
 'Plomeur',
 'Plogastel-Saint-Germain',
 'Ploudaniel',
 'Guipavas',
 'Plabennec',
 'Brest',
 'Plouzané',
 'Plouguin',
 'Anderlecht',
 'Sint-Agatha-Berchem',
 'Ganshoren',
 'Sint-Jans-Molenbeek',
 'Jette',
 'Koekelberg',
 'Forest',
 'Saint-Gilles',
 'Brussels',
 'Uccle',
 'Saint-Josse-ten-Noode',
 'Ixelles',
 'Schaerbeek',
 'Etterbeek',
 'Evere',
 'Watermael-Boitsfort',
 'Woluwe-Saint-Lambert',
 'Auderghem',
 'Woluwe-Saint-Pierre',
 'Busan',
 'Blythe',
 'Brawley',
 'Calexico',
 'El Centro',
 'Twentynine Palms',
 'Imperial',
 ...]

In [56]:
users['country'].value_counts()

country
China             33893
United States     22309
Brasil            14669
South Korea        5328
United Kingdom     4678
France             4612
Germany            4248
Spain              4065
Japan              2471
Australia          2234
Belgium            1227
Poland              252
Colombia             11
España                2
Deutschland           1
Name: count, dtype: int64

In [57]:
users['country'] = users['country'].replace(
    {'España': 'Spain', 'Deutschland': 'Germany'}
)

In [58]:
users['country'].value_counts()

country
China             33893
United States     22309
Brasil            14669
South Korea        5328
United Kingdom     4678
France             4612
Germany            4249
Spain              4067
Japan              2471
Australia          2234
Belgium            1227
Poland              252
Colombia             11
Name: count, dtype: int64

In [59]:
users['traffic_source'].unique()

<ArrowStringArray>
['Search', 'Display', 'Organic', 'Email', 'Facebook']
Length: 5, dtype: str

In [60]:
# users.to_csv('data/users_clean.csv', index=False)

5. Bảng products

In [61]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      29120 non-null  int64
 1   cost                    29120 non-null  float64
 2   category                29120 non-null  str
 3   name                    29118 non-null  str
 4   brand                   29096 non-null  str
 5   retail_price            29120 non-null  float64
 6   department              29120 non-null  str
 7   sku                     29120 non-null  str
 8   distribution_center_id  29120 non-null  int64
dtypes: float64(2), int64(2), str(5)
memory usage: 4.9 MB

In [62]:
products.head()

,id,cost,category,name,brand,retail_price,department,sku,distribution_center_id
0,13842,2.51875,Accessories,Low Profile Dyed Cotton Twill Cap - Navy W39S55D,MG,6.25,Women,EBD58B8A3F1D72F4206201DA62FB1204,1
1,13928,2.33835,Accessories,Low Profile Dyed Cotton Twill Cap - Putty W39S55D,MG,5.95,Women,2EAC42424D12436BDD6A5B8A88480CC3,1
2,14115,4.87956,Accessories,Enzyme Regular Solid Army Caps-Black W35S45D,MG,10.99,Women,EE364229B2791D1EF9355708EFF0BA34,1
3,14157,4.64877,Accessories,Enzyme Regular Solid Army Caps-Olive W35S45D (...,MG,10.99,Women,00BD13095D06C20B11A2993CA419D16B,1
4,14273,6.50793,Accessories,Washed Canvas Ivy Cap - Black W11S64C,MG,15.99,Women,F531DC20FDE20B7ADF3A73F52B71D0AF,1

In [63]:
products.isna().sum()

id                         0
cost                       0
category                   0
name                       2
brand                     24
retail_price               0
department                 0
sku                        0
distribution_center_id     0
dtype: int64

In [64]:
products.duplicated().sum()

np.int64(0)

Drop các cột không cần thiết cho phân tích

In [65]:
products = products.drop(columns=['name', 'sku', 'distribution_center_id'])

In [66]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            29120 non-null  int64
 1   cost          29120 non-null  float64
 2   category      29120 non-null  str
 3   brand         29096 non-null  str
 4   retail_price  29120 non-null  float64
 5   department    29120 non-null  str
dtypes: float64(2), int64(1), str(3)
memory usage: 2.0 MB

In [67]:
products[['cost', 'retail_price']].describe()

               cost  retail_price
count  29120.000000  29120.000000
mean      28.481774     59.220164
std       30.624681     65.888927
min        0.008300      0.020000
25%       11.275613     24.000000
50%       19.675081     39.990002
75%       34.440000     69.949997
max      557.151002    999.000000

In [68]:
products['brand'] = products['brand'].fillna('Unknown')

In [69]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            29120 non-null  int64
 1   cost          29120 non-null  float64
 2   category      29120 non-null  str
 3   brand         29120 non-null  str
 4   retail_price  29120 non-null  float64
 5   department    29120 non-null  str
dtypes: float64(2), int64(1), str(3)
memory usage: 2.0 MB

In [70]:
products['category'].unique()

<ArrowStringArray>
[                  'Accessories',                          'Plus',
                          'Swim',                        'Active',
               'Socks & Hosiery',                         'Socks',
                       'Dresses',                'Pants & Capris',
 'Fashion Hoodies & Sweatshirts',                        'Skirts',
             'Blazers & Jackets',                         'Suits',
                   'Tops & Tees',                      'Sweaters',
                        'Shorts',                         'Jeans',
                     'Maternity',                'Sleep & Lounge',
           'Suits & Sport Coats',                         'Pants',
                     'Intimates',             'Outerwear & Coats',
                     'Underwear',                      'Leggings',
           'Jumpsuits & Rompers',                 'Clothing Sets']
Length: 26, dtype: str

In [71]:
products['department'].unique()

<ArrowStringArray>
['Women', 'Men']
Length: 2, dtype: str

In [72]:
products['brand'].unique()

<ArrowStringArray>
[                           'MG',                            'MW',
                           '2XU',                           'AGB',
                           'BKE',                           'HDE',
                           'Huf',                           'ITC',
                           'Ice',                           'LNA',
 ...
            'Rumina Nursingwear',           'Affinitas Intimates',
           'Flying Monkey Jeans',         'CARRAIG DONN KNITWEAR',
        'Independent Trading Co',        'John Varvatos Star USA',
        'The Pajamagram Company',      'Rompers and Jumpsuits HS',
  'The Harris Tweed Of Scotland', 'What Goes Around Comes Around']
Length: 2757, dtype: str

In [73]:
# products.to_csv('data/products_clean.csv', index=False)